  CREATE OR REPLACE FUNCTION UDO_GET_FILE_CONTENTTYPE (A_FILENAME varchar2) return varchar2 is
      LL_RES varchar2(1000);
    begin
      case SUBSTR(A_FILENAME, INSTR(A_FILENAME, '.', -1))
        when '.x3d' then
          LL_RES := 'application/vnd.hzn-3d-crossword';
        when '.3gp' then
          LL_RES := 'video/3gpp';
        when '.3g2' then
          LL_RES := 'video/3gpp2';
        when '.mseq' then
          LL_RES := 'application/vnd.mseq';
        when '.pwn' then
          LL_RES := 'application/vnd.3m.post-it-notes';
        when '.plb' then
          LL_RES := 'application/vnd.3gpp.pic-bw-large';
        when '.psb' then
          LL_RES := 'application/vnd.3gpp.pic-bw-small';
        when '.pvb' then
          LL_RES := 'application/vnd.3gpp.pic-bw-var';
        when '.tcap' then
          LL_RES := 'application/vnd.3gpp2.tcap';
        when '.7z' then
          LL_RES := 'application/x-7z-compressed';
        when '.abw' then
          LL_RES := 'application/x-abiword';
        when '.ace' then
          LL_RES := 'application/x-ace-compressed';
        when '.acc' then
          LL_RES := 'application/vnd.americandynamics.acc';
        when '.acu' then
          LL_RES := 'application/vnd.acucobol';
        when '.atc' then
          LL_RES := 'application/vnd.acucorp';
        when '.adp' then
          LL_RES := 'audio/adpcm';
        when '.aab' then
          LL_RES := 'application/x-authorware-bin';
        when '.aam' then
          LL_RES := 'application/x-authorware-map';
        when '.aas' then
          LL_RES := 'application/x-authorware-seg';
        when '.air' then
          LL_RES := 'application/vnd.adobe.air-application-installer-package+zip';
        when '.swf' then
          LL_RES := 'application/x-shockwave-flash';
        when '.fxp' then
          LL_RES := 'application/vnd.adobe.fxp';
        when '.pdf' then
          LL_RES := 'application/pdf';
        when '.ppd' then
          LL_RES := 'application/vnd.cups-ppd';
        when '.dir' then
          LL_RES := 'application/x-director';
        when '.xdp' then
          LL_RES := 'application/vnd.adobe.xdp+xml';
        when '.xfdf' then
          LL_RES := 'application/vnd.adobe.xfdf';
        when '.aac' then
          LL_RES := 'audio/x-aac';
        when '.ahead' then
          LL_RES := 'application/vnd.ahead.space';
        when '.azf' then
          LL_RES := 'application/vnd.airzip.filesecure.azf';
        when '.azs' then
          LL_RES := 'application/vnd.airzip.filesecure.azs';
        when '.azw' then
          LL_RES := 'application/vnd.amazon.ebook';
        when '.ami' then
          LL_RES := 'application/vnd.amiga.ami';
        when 'N/A' then
          LL_RES := 'application/andrew-inset';
        when '.apk' then
          LL_RES := 'application/vnd.android.package-archive';
        when '.cii' then
          LL_RES := 'application/vnd.anser-web-certificate-issue-initiation';
        when '.fti' then
          LL_RES := 'application/vnd.anser-web-funds-transfer-initiation';
        when '.atx' then
          LL_RES := 'application/vnd.antix.game-component';
        when '.mpkg' then
          LL_RES := 'application/vnd.apple.installer+xml';
        when '.aw' then
          LL_RES := 'application/applixware';
        when '.les' then
          LL_RES := 'application/vnd.hhe.lesson-player';
        when '.swi' then
          LL_RES := 'application/vnd.aristanetworks.swi';
        when '.s' then
          LL_RES := 'text/x-asm';
        when '.atomcat' then
          LL_RES := 'application/atomcat+xml';
        when '.atomsvc' then
          LL_RES := 'application/atomsvc+xml';
        when '.atom, .xml' then
          LL_RES := 'application/atom+xml';
        when '.ac' then
          LL_RES := 'application/pkix-attr-cert';
        when '.aif' then
          LL_RES := 'audio/x-aiff';
        when '.avi' then
          LL_RES := 'video/x-msvideo';
        when '.aep' then
          LL_RES := 'application/vnd.audiograph';
        when '.dxf' then
          LL_RES := 'image/vnd.dxf';
        when '.dwf' then
          LL_RES := 'model/vnd.dwf';
        when '.par' then
          LL_RES := 'text/plain-bas';
        when '.bcpio' then
          LL_RES := 'application/x-bcpio';
        when '.bin' then
          LL_RES := 'application/octet-stream';
        when '.bmp' then
          LL_RES := 'image/bmp';
        when '.torrent' then
          LL_RES := 'application/x-bittorrent';
        when '.cod' then
          LL_RES := 'application/vnd.rim.cod';
        when '.mpm' then
          LL_RES := 'application/vnd.blueice.multipass';
        when '.bmi' then
          LL_RES := 'application/vnd.bmi';
        when '.sh' then
          LL_RES := 'application/x-sh';
        when '.btif' then
          LL_RES := 'image/prs.btif';
        when '.rep' then
          LL_RES := 'application/vnd.businessobjects';
        when '.bz' then
          LL_RES := 'application/x-bzip';
        when '.bz2' then
          LL_RES := 'application/x-bzip2';
        when '.csh' then
          LL_RES := 'application/x-csh';
        when '.c' then
          LL_RES := 'text/x-c';
        when '.cdxml' then
          LL_RES := 'application/vnd.chemdraw+xml';
        when '.css' then
          LL_RES := 'text/css';
        when '.cdx' then
          LL_RES := 'chemical/x-cdx';
        when '.cml' then
          LL_RES := 'chemical/x-cml';
        when '.csml' then
          LL_RES := 'chemical/x-csml';
        when '.cdbcmsg' then
          LL_RES := 'application/vnd.contact.cmsg';
        when '.cla' then
          LL_RES := 'application/vnd.claymore';
        when '.c4g' then
          LL_RES := 'application/vnd.clonk.c4group';
        when '.sub' then
          LL_RES := 'image/vnd.dvb.subtitle';
        when '.cdmia' then
          LL_RES := 'application/cdmi-capability';
        when '.cdmic' then
          LL_RES := 'application/cdmi-container';
        when '.cdmid' then
          LL_RES := 'application/cdmi-domain';
        when '.cdmio' then
          LL_RES := 'application/cdmi-object';
        when '.cdmiq' then
          LL_RES := 'application/cdmi-queue';
        when '.c11amc' then
          LL_RES := 'application/vnd.cluetrust.cartomobile-config';
        when '.c11amz' then
          LL_RES := 'application/vnd.cluetrust.cartomobile-config-pkg';
        when '.ras' then
          LL_RES := 'image/x-cmu-raster';
        when '.dae' then
          LL_RES := 'model/vnd.collada+xml';
        when '.csv' then
          LL_RES := 'text/csv';
        when '.cpt' then
          LL_RES := 'application/mac-compactpro';
        when '.wmlc' then
          LL_RES := 'application/vnd.wap.wmlc';
        when '.cgm' then
          LL_RES := 'image/cgm';
        when '.ice' then
          LL_RES := 'x-conference/x-cooltalk';
        when '.cmx' then
          LL_RES := 'image/x-cmx';
        when '.xar' then
          LL_RES := 'application/vnd.xara';
        when '.cmc' then
          LL_RES := 'application/vnd.cosmocaller';
        when '.cpio' then
          LL_RES := 'application/x-cpio';
        when '.clkx' then
          LL_RES := 'application/vnd.crick.clicker';
        when '.clkk' then
          LL_RES := 'application/vnd.crick.clicker.keyboard';
        when '.clkp' then
          LL_RES := 'application/vnd.crick.clicker.palette';
        when '.clkt' then
          LL_RES := 'application/vnd.crick.clicker.template';
        when '.clkw' then
          LL_RES := 'application/vnd.crick.clicker.wordbank';
        when '.wbs' then
          LL_RES := 'application/vnd.criticaltools.wbs+xml';
        when '.cryptonote' then
          LL_RES := 'application/vnd.rig.cryptonote';
        when '.cif' then
          LL_RES := 'chemical/x-cif';
        when '.cmdf' then
          LL_RES := 'chemical/x-cmdf';
        when '.cu' then
          LL_RES := 'application/cu-seeme';
        when '.cww' then
          LL_RES := 'application/prs.cww';
        when '.curl' then
          LL_RES := 'text/vnd.curl';
        when '.dcurl' then
          LL_RES := 'text/vnd.curl.dcurl';
        when '.mcurl' then
          LL_RES := 'text/vnd.curl.mcurl';
        when '.scurl' then
          LL_RES := 'text/vnd.curl.scurl';
        when '.car' then
          LL_RES := 'application/vnd.curl.car';
        when '.pcurl' then
          LL_RES := 'application/vnd.curl.pcurl';
        when '.cmp' then
          LL_RES := 'application/vnd.yellowriver-custom-menu';
        when '.dssc' then
          LL_RES := 'application/dssc+der';
        when '.xdssc' then
          LL_RES := 'application/dssc+xml';
        when '.deb' then
          LL_RES := 'application/x-debian-package';
        when '.uva' then
          LL_RES := 'audio/vnd.dece.audio';
        when '.uvi' then
          LL_RES := 'image/vnd.dece.graphic';
        when '.uvh' then
          LL_RES := 'video/vnd.dece.hd';
        when '.uvm' then
          LL_RES := 'video/vnd.dece.mobile';
        when '.uvu' then
          LL_RES := 'video/vnd.uvvu.mp4';
        when '.uvp' then
          LL_RES := 'video/vnd.dece.pd';
        when '.uvs' then
          LL_RES := 'video/vnd.dece.sd';
        when '.uvv' then
          LL_RES := 'video/vnd.dece.video';
        when '.dvi' then
          LL_RES := 'application/x-dvi';
        when '.seed' then
          LL_RES := 'application/vnd.fdsn.seed';
        when '.dtb' then
          LL_RES := 'application/x-dtbook+xml';
        when '.res' then
          LL_RES := 'application/x-dtbresource+xml';
        when '.ait' then
          LL_RES := 'application/vnd.dvb.ait';
        when '.svc' then
          LL_RES := 'application/vnd.dvb.service';
        when '.eol' then
          LL_RES := 'audio/vnd.digital-winds';
        when '.djvu' then
          LL_RES := 'image/vnd.djvu';
        when '.dtd' then
          LL_RES := 'application/xml-dtd';
        when '.mlp' then
          LL_RES := 'application/vnd.dolby.mlp';
        when '.wad' then
          LL_RES := 'application/x-doom';
        when '.dpg' then
          LL_RES := 'application/vnd.dpgraph';
        when '.dra' then
          LL_RES := 'audio/vnd.dra';
        when '.dfac' then
          LL_RES := 'application/vnd.dreamfactory';
        when '.dts' then
          LL_RES := 'audio/vnd.dts';
        when '.dtshd' then
          LL_RES := 'audio/vnd.dts.hd';
        when '.dwg' then
          LL_RES := 'image/vnd.dwg';
        when '.geo' then
          LL_RES := 'application/vnd.dynageo';
        when '.es' then
          LL_RES := 'application/ecmascript';
        when '.mag' then
          LL_RES := 'application/vnd.ecowin.chart';
        when '.mmr' then
          LL_RES := 'image/vnd.fujixerox.edmics-mmr';
        when '.rlc' then
          LL_RES := 'image/vnd.fujixerox.edmics-rlc';
        when '.exi' then
          LL_RES := 'application/exi';
        when '.mgz' then
          LL_RES := 'application/vnd.proteus.magazine';
        when '.epub' then
          LL_RES := 'application/epub+zip';
        when '.eml' then
          LL_RES := 'message/rfc822';
        when '.nml' then
          LL_RES := 'application/vnd.enliven';
        when '.xpr' then
          LL_RES := 'application/vnd.is-xpr';
        when '.xif' then
          LL_RES := 'image/vnd.xiff';
        when '.xfdl' then
          LL_RES := 'application/vnd.xfdl';
        when '.emma' then
          LL_RES := 'application/emma+xml';
        when '.ez2' then
          LL_RES := 'application/vnd.ezpix-album';
        when '.ez3' then
          LL_RES := 'application/vnd.ezpix-package';
        when '.fst' then
          LL_RES := 'image/vnd.fst';
        when '.fvt' then
          LL_RES := 'video/vnd.fvt';
        when '.fbs' then
          LL_RES := 'image/vnd.fastbidsheet';
        when '.fe_launch' then
          LL_RES := 'application/vnd.denovo.fcselayout-link';
        when '.f4v' then
          LL_RES := 'video/x-f4v';
        when '.flv' then
          LL_RES := 'video/x-flv';
        when '.fpx' then
          LL_RES := 'image/vnd.fpx';
        when '.npx' then
          LL_RES := 'image/vnd.net-fpx';
        when '.flx' then
          LL_RES := 'text/vnd.fmi.flexstor';
        when '.fli' then
          LL_RES := 'video/x-fli';
        when '.ftc' then
          LL_RES := 'application/vnd.fluxtime.clip';
        when '.fdf' then
          LL_RES := 'application/vnd.fdf';
        when '.f' then
          LL_RES := 'text/x-fortran';
        when '.mif' then
          LL_RES := 'application/vnd.mif';
        when '.fm' then
          LL_RES := 'application/vnd.framemaker';
        when '.fh' then
          LL_RES := 'image/x-freehand';
        when '.fsc' then
          LL_RES := 'application/vnd.fsc.weblaunch';
        when '.fnc' then
          LL_RES := 'application/vnd.frogans.fnc';
        when '.ltf' then
          LL_RES := 'application/vnd.frogans.ltf';
        when '.ddd' then
          LL_RES := 'application/vnd.fujixerox.ddd';
        when '.xdw' then
          LL_RES := 'application/vnd.fujixerox.docuworks';
        when '.xbd' then
          LL_RES := 'application/vnd.fujixerox.docuworks.binder';
        when '.oas' then
          LL_RES := 'application/vnd.fujitsu.oasys';
        when '.oa2' then
          LL_RES := 'application/vnd.fujitsu.oasys2';
        when '.oa3' then
          LL_RES := 'application/vnd.fujitsu.oasys3';
        when '.fg5' then
          LL_RES := 'application/vnd.fujitsu.oasysgp';
        when '.bh2' then
          LL_RES := 'application/vnd.fujitsu.oasysprs';
        when '.spl' then
          LL_RES := 'application/x-futuresplash';
        when '.fzs' then
          LL_RES := 'application/vnd.fuzzysheet';
        when '.g3' then
          LL_RES := 'image/g3fax';
        when '.gmx' then
          LL_RES := 'application/vnd.gmx';
        when '.gtw' then
          LL_RES := 'model/vnd.gtw';
        when '.txd' then
          LL_RES := 'application/vnd.genomatix.tuxedo';
        when '.ggb' then
          LL_RES := 'application/vnd.geogebra.file';
        when '.ggt' then
          LL_RES := 'application/vnd.geogebra.tool';
        when '.gdl' then
          LL_RES := 'model/vnd.gdl';
        when '.gex' then
          LL_RES := 'application/vnd.geometry-explorer';
        when '.gxt' then
          LL_RES := 'application/vnd.geonext';
        when '.g2w' then
          LL_RES := 'application/vnd.geoplan';
        when '.g3w' then
          LL_RES := 'application/vnd.geospace';
        when '.gsf' then
          LL_RES := 'application/x-font-ghostscript';
        when '.bdf' then
          LL_RES := 'application/x-font-bdf';
        when '.gtar' then
          LL_RES := 'application/x-gtar';
        when '.texinfo' then
          LL_RES := 'application/x-texinfo';
        when '.gnumeric' then
          LL_RES := 'application/x-gnumeric';
        when '.kml' then
          LL_RES := 'application/vnd.google-earth.kml+xml';
        when '.kmz' then
          LL_RES := 'application/vnd.google-earth.kmz';
        when '.gqf' then
          LL_RES := 'application/vnd.grafeq';
        when '.gif' then
          LL_RES := 'image/gif';
        when '.gv' then
          LL_RES := 'text/vnd.graphviz';
        when '.gac' then
          LL_RES := 'application/vnd.groove-account';
        when '.ghf' then
          LL_RES := 'application/vnd.groove-help';
        when '.gim' then
          LL_RES := 'application/vnd.groove-identity-message';
        when '.grv' then
          LL_RES := 'application/vnd.groove-injector';
        when '.gtm' then
          LL_RES := 'application/vnd.groove-tool-message';
        when '.tpl' then
          LL_RES := 'application/vnd.groove-tool-template';
        when '.vcg' then
          LL_RES := 'application/vnd.groove-vcard';
        when '.h261' then
          LL_RES := 'video/h261';
        when '.h263' then
          LL_RES := 'video/h263';
        when '.h264' then
          LL_RES := 'video/h264';
        when '.hpid' then
          LL_RES := 'application/vnd.hp-hpid';
        when '.hps' then
          LL_RES := 'application/vnd.hp-hps';
        when '.hdf' then
          LL_RES := 'application/x-hdf';
        when '.rip' then
          LL_RES := 'audio/vnd.rip';
        when '.hbci' then
          LL_RES := 'application/vnd.hbci';
        when '.jlt' then
          LL_RES := 'application/vnd.hp-jlyt';
        when '.pcl' then
          LL_RES := 'application/vnd.hp-pcl';
        when '.hpgl' then
          LL_RES := 'application/vnd.hp-hpgl';
        when '.hvs' then
          LL_RES := 'application/vnd.yamaha.hv-script';
        when '.hvd' then
          LL_RES := 'application/vnd.yamaha.hv-dic';
        when '.hvp' then
          LL_RES := 'application/vnd.yamaha.hv-voice';
        when '.sfd-hdstx' then
          LL_RES := 'application/vnd.hydrostatix.sof-data';
        when '.stk' then
          LL_RES := 'application/hyperstudio';
        when '.hal' then
          LL_RES := 'application/vnd.hal+xml';
        when '.html' then
          LL_RES := 'text/html';
        when '.irm' then
          LL_RES := 'application/vnd.ibm.rights-management';
        when '.sc' then
          LL_RES := 'application/vnd.ibm.secure-container';
        when '.ics' then
          LL_RES := 'text/calendar';
        when '.icc' then
          LL_RES := 'application/vnd.iccprofile';
        when '.ico' then
          LL_RES := 'image/x-icon';
        when '.igl' then
          LL_RES := 'application/vnd.igloader';
        when '.ief' then
          LL_RES := 'image/ief';
        when '.ivp' then
          LL_RES := 'application/vnd.immervision-ivp';
        when '.ivu' then
          LL_RES := 'application/vnd.immervision-ivu';
        when '.rif' then
          LL_RES := 'application/reginfo+xml';
        when '.3dml' then
          LL_RES := 'text/vnd.in3d.3dml';
        when '.spot' then
          LL_RES := 'text/vnd.in3d.spot';
        when '.igs' then
          LL_RES := 'model/iges';
        when '.i2g' then
          LL_RES := 'application/vnd.intergeo';
        when '.cdy' then
          LL_RES := 'application/vnd.cinderella';
        when '.xpw' then
          LL_RES := 'application/vnd.intercon.formnet';
        when '.fcs' then
          LL_RES := 'application/vnd.isac.fcs';
        when '.ipfix' then
          LL_RES := 'application/ipfix';
        when '.cer' then
          LL_RES := 'application/pkix-cert';
        when '.pki' then
          LL_RES := 'application/pkixcmp';
        when '.crl' then
          LL_RES := 'application/pkix-crl';
        when '.pkipath' then
          LL_RES := 'application/pkix-pkipath';
        when '.igm' then
          LL_RES := 'application/vnd.insors.igm';
        when '.rcprofile' then
          LL_RES := 'application/vnd.ipunplugged.rcprofile';
        when '.irp' then
          LL_RES := 'application/vnd.irepository.package+xml';
        when '.jad' then
          LL_RES := 'text/vnd.sun.j2me.app-descriptor';
        when '.jar' then
          LL_RES := 'application/java-archive';
        when '.class' then
          LL_RES := 'application/java-vm';
        when '.jnlp' then
          LL_RES := 'application/x-java-jnlp-file';
        when '.ser' then
          LL_RES := 'application/java-serialized-object';
        when '.java' then
          LL_RES := 'text/x-java-source,java';
        when '.js' then
          LL_RES := 'application/javascript';
        when '.json' then
          LL_RES := 'application/json';
        when '.joda' then
          LL_RES := 'application/vnd.joost.joda-archive';
        when '.jpm' then
          LL_RES := 'video/jpm';
        when '.jpeg, .jpg' then
          LL_RES := 'image/jpeg';
        when '.jpgv' then
          LL_RES := 'video/jpeg';
        when '.ktz' then
          LL_RES := 'application/vnd.kahootz';
        when '.mmd' then
          LL_RES := 'application/vnd.chipnuts.karaoke-mmd';
        when '.karbon' then
          LL_RES := 'application/vnd.kde.karbon';
        when '.chrt' then
          LL_RES := 'application/vnd.kde.kchart';
        when '.kfo' then
          LL_RES := 'application/vnd.kde.kformula';
        when '.flw' then
          LL_RES := 'application/vnd.kde.kivio';
        when '.kon' then
          LL_RES := 'application/vnd.kde.kontour';
        when '.kpr' then
          LL_RES := 'application/vnd.kde.kpresenter';
        when '.ksp' then
          LL_RES := 'application/vnd.kde.kspread';
        when '.kwd' then
          LL_RES := 'application/vnd.kde.kword';
        when '.htke' then
          LL_RES := 'application/vnd.kenameaapp';
        when '.kia' then
          LL_RES := 'application/vnd.kidspiration';
        when '.kne' then
          LL_RES := 'application/vnd.kinar';
        when '.sse' then
          LL_RES := 'application/vnd.kodak-descriptor';
        when '.lasxml' then
          LL_RES := 'application/vnd.las.las+xml';
        when '.latex' then
          LL_RES := 'application/x-latex';
        when '.lbd' then
          LL_RES := 'application/vnd.llamagraphics.life-balance.desktop';
        when '.lbe' then
          LL_RES := 'application/vnd.llamagraphics.life-balance.exchange+xml';
        when '.jam' then
          LL_RES := 'application/vnd.jam';
        when '.123' then
          LL_RES := 'application/vnd.lotus-1-2-3';
        when '.apr' then
          LL_RES := 'application/vnd.lotus-approach';
        when '.pre' then
          LL_RES := 'application/vnd.lotus-freelance';
        when '.nsf' then
          LL_RES := 'application/vnd.lotus-notes';
        when '.org' then
          LL_RES := 'application/vnd.lotus-organizer';
        when '.scm' then
          LL_RES := 'application/vnd.lotus-screencam';
        when '.lwp' then
          LL_RES := 'application/vnd.lotus-wordpro';
        when '.lvp' then
          LL_RES := 'audio/vnd.lucent.voice';
        when '.m3u' then
          LL_RES := 'audio/x-mpegurl';
        when '.m4v' then
          LL_RES := 'video/x-m4v';
        when '.hqx' then
          LL_RES := 'application/mac-binhex40';
        when '.portpkg' then
          LL_RES := 'application/vnd.macports.portpkg';
        when '.mgp' then
          LL_RES := 'application/vnd.osgeo.mapguide.package';
        when '.mrc' then
          LL_RES := 'application/marc';
        when '.mrcx' then
          LL_RES := 'application/marcxml+xml';
        when '.mxf' then
          LL_RES := 'application/mxf';
        when '.nbp' then
          LL_RES := 'application/vnd.wolfram.player';
        when '.ma' then
          LL_RES := 'application/mathematica';
        when '.mathml' then
          LL_RES := 'application/mathml+xml';
        when '.mbox' then
          LL_RES := 'application/mbox';
        when '.mc1' then
          LL_RES := 'application/vnd.medcalcdata';
        when '.mscml' then
          LL_RES := 'application/mediaservercontrol+xml';
        when '.cdkey' then
          LL_RES := 'application/vnd.mediastation.cdkey';
        when '.mwf' then
          LL_RES := 'application/vnd.mfer';
        when '.mfm' then
          LL_RES := 'application/vnd.mfmp';
        when '.msh' then
          LL_RES := 'model/mesh';
        when '.mads' then
          LL_RES := 'application/mads+xml';
        when '.mets' then
          LL_RES := 'application/mets+xml';
        when '.mods' then
          LL_RES := 'application/mods+xml';
        when '.meta4' then
          LL_RES := 'application/metalink4+xml';
        when '.potm' then
          LL_RES := 'application/vnd.ms-powerpoint.template.macroenabled.12';
        when '.docm' then
          LL_RES := 'application/vnd.ms-word.document.macroenabled.12';
        when '.dotm' then
          LL_RES := 'application/vnd.ms-word.template.macroenabled.12';
        when '.mcd' then
          LL_RES := 'application/vnd.mcd';
        when '.flo' then
          LL_RES := 'application/vnd.micrografx.flo';
        when '.igx' then
          LL_RES := 'application/vnd.micrografx.igx';
        when '.es3' then
          LL_RES := 'application/vnd.eszigno3+xml';
        when '.mdb' then
          LL_RES := 'application/x-msaccess';
        when '.asf' then
          LL_RES := 'video/x-ms-asf';
        when '.exe' then
          LL_RES := 'application/x-msdownload';
        when '.cil' then
          LL_RES := 'application/vnd.ms-artgalry';
        when '.cab' then
          LL_RES := 'application/vnd.ms-cab-compressed';
        when '.ims' then
          LL_RES := 'application/vnd.ms-ims';
        when '.application' then
          LL_RES := 'application/x-ms-application';
        when '.clp' then
          LL_RES := 'application/x-msclip';
        when '.mdi' then
          LL_RES := 'image/vnd.ms-modi';
        when '.eot' then
          LL_RES := 'application/vnd.ms-fontobject';
        when '.xls' then
          LL_RES := 'application/vnd.ms-excel';
        when '.xlam' then
          LL_RES := 'application/vnd.ms-excel.addin.macroenabled.12';
        when '.xlsb' then
          LL_RES := 'application/vnd.ms-excel.sheet.binary.macroenabled.12';
        when '.xltm' then
          LL_RES := 'application/vnd.ms-excel.template.macroenabled.12';
        when '.xlsm' then
          LL_RES := 'application/vnd.ms-excel.sheet.macroenabled.12';
        when '.chm' then
          LL_RES := 'application/vnd.ms-htmlhelp';
        when '.crd' then
          LL_RES := 'application/x-mscardfile';
        when '.lrm' then
          LL_RES := 'application/vnd.ms-lrm';
        when '.mvb' then
          LL_RES := 'application/x-msmediaview';
        when '.mny' then
          LL_RES := 'application/x-msmoney';
        when '.pptx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
        when '.sldx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.presentationml.slide';
        when '.ppsx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.presentationml.slideshow';
        when '.potx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.presentationml.template';
        when '.xlsx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
        when '.xltx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.spreadsheetml.template';
        when '.docx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
        when '.dotx' then
          LL_RES := 'application/vnd.openxmlformats-officedocument.wordprocessingml.template';
        when '.obd' then
          LL_RES := 'application/x-msbinder';
        when '.thmx' then
          LL_RES := 'application/vnd.ms-officetheme';
        when '.onetoc' then
          LL_RES := 'application/onenote';
        when '.pya' then
          LL_RES := 'audio/vnd.ms-playready.media.pya';
        when '.pyv' then
          LL_RES := 'video/vnd.ms-playready.media.pyv';
        when '.ppt' then
          LL_RES := 'application/vnd.ms-powerpoint';
        when '.ppam' then
          LL_RES := 'application/vnd.ms-powerpoint.addin.macroenabled.12';
        when '.sldm' then
          LL_RES := 'application/vnd.ms-powerpoint.slide.macroenabled.12';
        when '.pptm' then
          LL_RES := 'application/vnd.ms-powerpoint.presentation.macroenabled.12';
        when '.ppsm' then
          LL_RES := 'application/vnd.ms-powerpoint.slideshow.macroenabled.12';
        when '.mpp' then
          LL_RES := 'application/vnd.ms-project';
        when '.pub' then
          LL_RES := 'application/x-mspublisher';
        when '.scd' then
          LL_RES := 'application/x-msschedule';
        when '.xap' then
          LL_RES := 'application/x-silverlight-app';
        when '.stl' then
          LL_RES := 'application/vnd.ms-pki.stl';
        when '.cat' then
          LL_RES := 'application/vnd.ms-pki.seccat';
        when '.vsd' then
          LL_RES := 'application/vnd.visio';
        when '.wm' then
          LL_RES := 'video/x-ms-wm';
        when '.wma' then
          LL_RES := 'audio/x-ms-wma';
        when '.wax' then
          LL_RES := 'audio/x-ms-wax';
        when '.wmx' then
          LL_RES := 'video/x-ms-wmx';
        when '.wmd' then
          LL_RES := 'application/x-ms-wmd';
        when '.wpl' then
          LL_RES := 'application/vnd.ms-wpl';
        when '.wmz' then
          LL_RES := 'application/x-ms-wmz';
        when '.wmv' then
          LL_RES := 'video/x-ms-wmv';
        when '.wvx' then
          LL_RES := 'video/x-ms-wvx';
        when '.wmf' then
          LL_RES := 'application/x-msmetafile';
        when '.trm' then
          LL_RES := 'application/x-msterminal';
        when '.doc' then
          LL_RES := 'application/msword';
        when '.wri' then
          LL_RES := 'application/x-mswrite';
        when '.wps' then
          LL_RES := 'application/vnd.ms-works';
        when '.xbap' then
          LL_RES := 'application/x-ms-xbap';
        when '.xps' then
          LL_RES := 'application/vnd.ms-xpsdocument';
        when '.mid' then
          LL_RES := 'audio/midi';
        when '.mpy' then
          LL_RES := 'application/vnd.ibm.minipay';
        when '.afp' then
          LL_RES := 'application/vnd.ibm.modcap';
        when '.rms' then
          LL_RES := 'application/vnd.jcp.javame.midlet-rms';
        when '.tmo' then
          LL_RES := 'application/vnd.tmobile-livetv';
        when '.prc' then
          LL_RES := 'application/x-mobipocket-ebook';
        when '.mbk' then
          LL_RES := 'application/vnd.mobius.mbk';
        when '.dis' then
          LL_RES := 'application/vnd.mobius.dis';
        when '.plc' then
          LL_RES := 'application/vnd.mobius.plc';
        when '.mqy' then
          LL_RES := 'application/vnd.mobius.mqy';
        when '.msl' then
          LL_RES := 'application/vnd.mobius.msl';
        when '.txf' then
          LL_RES := 'application/vnd.mobius.txf';
        when '.daf' then
          LL_RES := 'application/vnd.mobius.daf';
        when '.fly' then
          LL_RES := 'text/vnd.fly';
        when '.mpc' then
          LL_RES := 'application/vnd.mophun.certificate';
        when '.mpn' then
          LL_RES := 'application/vnd.mophun.application';
        when '.mj2' then
          LL_RES := 'video/mj2';
        when '.mpga' then
          LL_RES := 'audio/mpeg';
        when '.mxu' then
          LL_RES := 'video/vnd.mpegurl';
        when '.mpeg' then
          LL_RES := 'video/mpeg';
        when '.m21' then
          LL_RES := 'application/mp21';
        when '.mp4a' then
          LL_RES := 'audio/mp4';
        when '.mp4' then
          LL_RES := 'video/mp4';
        when '.mp4' then
          LL_RES := 'application/mp4';
        when '.m3u8' then
          LL_RES := 'application/vnd.apple.mpegurl';
        when '.mus' then
          LL_RES := 'application/vnd.musician';
        when '.msty' then
          LL_RES := 'application/vnd.muvee.style';
        when '.mxml' then
          LL_RES := 'application/xv+xml';
        when '.ngdat' then
          LL_RES := 'application/vnd.nokia.n-gage.data';
        when '.n-gage' then
          LL_RES := 'application/vnd.nokia.n-gage.symbian.install';
        when '.ncx' then
          LL_RES := 'application/x-dtbncx+xml';
        when '.nc' then
          LL_RES := 'application/x-netcdf';
        when '.nlu' then
          LL_RES := 'application/vnd.neurolanguage.nlu';
        when '.dna' then
          LL_RES := 'application/vnd.dna';
        when '.nnd' then
          LL_RES := 'application/vnd.noblenet-directory';
        when '.nns' then
          LL_RES := 'application/vnd.noblenet-sealer';
        when '.nnw' then
          LL_RES := 'application/vnd.noblenet-web';
        when '.rpst' then
          LL_RES := 'application/vnd.nokia.radio-preset';
        when '.rpss' then
          LL_RES := 'application/vnd.nokia.radio-presets';
        when '.n3' then
          LL_RES := 'text/n3';
        when '.edm' then
          LL_RES := 'application/vnd.novadigm.edm';
        when '.edx' then
          LL_RES := 'application/vnd.novadigm.edx';
        when '.ext' then
          LL_RES := 'application/vnd.novadigm.ext';
        when '.gph' then
          LL_RES := 'application/vnd.flographit';
        when '.ecelp4800' then
          LL_RES := 'audio/vnd.nuera.ecelp4800';
        when '.ecelp7470' then
          LL_RES := 'audio/vnd.nuera.ecelp7470';
        when '.ecelp9600' then
          LL_RES := 'audio/vnd.nuera.ecelp9600';
        when '.oda' then
          LL_RES := 'application/oda';
        when '.ogx' then
          LL_RES := 'application/ogg';
        when '.oga' then
          LL_RES := 'audio/ogg';
        when '.ogv' then
          LL_RES := 'video/ogg';
        when '.dd2' then
          LL_RES := 'application/vnd.oma.dd2+xml';
        when '.oth' then
          LL_RES := 'application/vnd.oasis.opendocument.text-web';
        when '.opf' then
          LL_RES := 'application/oebps-package+xml';
        when '.qbo' then
          LL_RES := 'application/vnd.intu.qbo';
        when '.oxt' then
          LL_RES := 'application/vnd.openofficeorg.extension';
        when '.osf' then
          LL_RES := 'application/vnd.yamaha.openscoreformat';
        when '.weba' then
          LL_RES := 'audio/webm';
        when '.webm' then
          LL_RES := 'video/webm';
        when '.odc' then
          LL_RES := 'application/vnd.oasis.opendocument.chart';
        when '.otc' then
          LL_RES := 'application/vnd.oasis.opendocument.chart-template';
        when '.odb' then
          LL_RES := 'application/vnd.oasis.opendocument.database';
        when '.odf' then
          LL_RES := 'application/vnd.oasis.opendocument.formula';
        when '.odft' then
          LL_RES := 'application/vnd.oasis.opendocument.formula-template';
        when '.odg' then
          LL_RES := 'application/vnd.oasis.opendocument.graphics';
        when '.otg' then
          LL_RES := 'application/vnd.oasis.opendocument.graphics-template';
        when '.odi' then
          LL_RES := 'application/vnd.oasis.opendocument.image';
        when '.oti' then
          LL_RES := 'application/vnd.oasis.opendocument.image-template';
        when '.odp' then
          LL_RES := 'application/vnd.oasis.opendocument.presentation';
        when '.otp' then
          LL_RES := 'application/vnd.oasis.opendocument.presentation-template';
        when '.ods' then
          LL_RES := 'application/vnd.oasis.opendocument.spreadsheet';
        when '.ots' then
          LL_RES := 'application/vnd.oasis.opendocument.spreadsheet-template';
        when '.odt' then
          LL_RES := 'application/vnd.oasis.opendocument.text';
        when '.odm' then
          LL_RES := 'application/vnd.oasis.opendocument.text-master';
        when '.ott' then
          LL_RES := 'application/vnd.oasis.opendocument.text-template';
        when '.ktx' then
          LL_RES := 'image/ktx';
        when '.sxc' then
          LL_RES := 'application/vnd.sun.xml.calc';
        when '.stc' then
          LL_RES := 'application/vnd.sun.xml.calc.template';
        when '.sxd' then
          LL_RES := 'application/vnd.sun.xml.draw';
        when '.std' then
          LL_RES := 'application/vnd.sun.xml.draw.template';
        when '.sxi' then
          LL_RES := 'application/vnd.sun.xml.impress';
        when '.sti' then
          LL_RES := 'application/vnd.sun.xml.impress.template';
        when '.sxm' then
          LL_RES := 'application/vnd.sun.xml.math';
        when '.sxw' then
          LL_RES := 'application/vnd.sun.xml.writer';
        when '.sxg' then
          LL_RES := 'application/vnd.sun.xml.writer.global';
        when '.stw' then
          LL_RES := 'application/vnd.sun.xml.writer.template';
        when '.otf' then
          LL_RES := 'application/x-font-otf';
        when '.osfpvg' then
          LL_RES := 'application/vnd.yamaha.openscoreformat.osfpvg+xml';
        when '.dp' then
          LL_RES := 'application/vnd.osgi.dp';
        when '.pdb' then
          LL_RES := 'application/vnd.palm';
        when '.p' then
          LL_RES := 'text/x-pascal';
        when '.paw' then
          LL_RES := 'application/vnd.pawaafile';
        when '.pclxl' then
          LL_RES := 'application/vnd.hp-pclxl';
        when '.efif' then
          LL_RES := 'application/vnd.picsel';
        when '.pcx' then
          LL_RES := 'image/x-pcx';
        when '.psd' then
          LL_RES := 'image/vnd.adobe.photoshop';
        when '.prf' then
          LL_RES := 'application/pics-rules';
        when '.pic' then
          LL_RES := 'image/x-pict';
        when '.chat' then
          LL_RES := 'application/x-chat';
        when '.p10' then
          LL_RES := 'application/pkcs10';
        when '.p12' then
          LL_RES := 'application/x-pkcs12';
        when '.p7m' then
          LL_RES := 'application/pkcs7-mime';
        when '.p7s' then
          LL_RES := 'application/pkcs7-signature';
        when '.p7r' then
          LL_RES := 'application/x-pkcs7-certreqresp';
        when '.p7b' then
          LL_RES := 'application/x-pkcs7-certificates';
        when '.p8' then
          LL_RES := 'application/pkcs8';
        when '.plf' then
          LL_RES := 'application/vnd.pocketlearn';
        when '.pnm' then
          LL_RES := 'image/x-portable-anymap';
        when '.pbm' then
          LL_RES := 'image/x-portable-bitmap';
        when '.pcf' then
          LL_RES := 'application/x-font-pcf';
        when '.pfr' then
          LL_RES := 'application/font-tdpfr';
        when '.pgn' then
          LL_RES := 'application/x-chess-pgn';
        when '.pgm' then
          LL_RES := 'image/x-portable-graymap';
        when '.png' then
          LL_RES := 'image/png';
        when '.ppm' then
          LL_RES := 'image/x-portable-pixmap';
        when '.pskcxml' then
          LL_RES := 'application/pskc+xml';
        when '.pml' then
          LL_RES := 'application/vnd.ctc-posml';
        when '.ai' then
          LL_RES := 'application/postscript';
        when '.pfa' then
          LL_RES := 'application/x-font-type1';
        when '.pbd' then
          LL_RES := 'application/vnd.powerbuilder6';
        when '.box' then
          LL_RES := 'application/vnd.previewsystems.box';
        when '.ptid' then
          LL_RES := 'application/vnd.pvi.ptid1';
        when '.pls' then
          LL_RES := 'application/pls+xml';
        when '.str' then
          LL_RES := 'application/vnd.pg.format';
        when '.ei6' then
          LL_RES := 'application/vnd.pg.osasli';
        when '.dsc' then
          LL_RES := 'text/prs.lines.tag';
        when '.psf' then
          LL_RES := 'application/x-font-linux-psf';
        when '.qps' then
          LL_RES := 'application/vnd.publishare-delta-tree';
        when '.wg' then
          LL_RES := 'application/vnd.pmi.widget';
        when '.qxd' then
          LL_RES := 'application/vnd.quark.quarkxpress';
        when '.esf' then
          LL_RES := 'application/vnd.epson.esf';
        when '.msf' then
          LL_RES := 'application/vnd.epson.msf';
        when '.ssf' then
          LL_RES := 'application/vnd.epson.ssf';
        when '.qam' then
          LL_RES := 'application/vnd.epson.quickanime';
        when '.qfx' then
          LL_RES := 'application/vnd.intu.qfx';
        when '.qt' then
          LL_RES := 'video/quicktime';
        when '.rar' then
          LL_RES := 'application/x-rar-compressed';
        when '.ram' then
          LL_RES := 'audio/x-pn-realaudio';
        when '.rmp' then
          LL_RES := 'audio/x-pn-realaudio-plugin';
        when '.rsd' then
          LL_RES := 'application/rsd+xml';
        when '.rm' then
          LL_RES := 'application/vnd.rn-realmedia';
        when '.bed' then
          LL_RES := 'application/vnd.realvnc.bed';
        when '.mxl' then
          LL_RES := 'application/vnd.recordare.musicxml';
        when '.musicxml' then
          LL_RES := 'application/vnd.recordare.musicxml+xml';
        when '.rnc' then
          LL_RES := 'application/relax-ng-compact-syntax';
        when '.rdz' then
          LL_RES := 'application/vnd.data-vision.rdz';
        when '.rdf' then
          LL_RES := 'application/rdf+xml';
        when '.rp9' then
          LL_RES := 'application/vnd.cloanto.rp9';
        when '.jisp' then
          LL_RES := 'application/vnd.jisp';
        when '.rtf' then
          LL_RES := 'application/rtf';
        when '.rtx' then
          LL_RES := 'text/richtext';
        when '.link66' then
          LL_RES := 'application/vnd.route66.link66+xml';
        when '.rss, .xml' then
          LL_RES := 'application/rss+xml';
        when '.shf' then
          LL_RES := 'application/shf+xml';
        when '.st' then
          LL_RES := 'application/vnd.sailingtracker.track';
        when '.svg' then
          LL_RES := 'image/svg+xml';
        when '.sus' then
          LL_RES := 'application/vnd.sus-calendar';
        when '.sru' then
          LL_RES := 'application/sru+xml';
        when '.setpay' then
          LL_RES := 'application/set-payment-initiation';
        when '.setreg' then
          LL_RES := 'application/set-registration-initiation';
        when '.sema' then
          LL_RES := 'application/vnd.sema';
        when '.semd' then
          LL_RES := 'application/vnd.semd';
        when '.semf' then
          LL_RES := 'application/vnd.semf';
        when '.see' then
          LL_RES := 'application/vnd.seemail';
        when '.snf' then
          LL_RES := 'application/x-font-snf';
        when '.spq' then
          LL_RES := 'application/scvp-vp-request';
        when '.spp' then
          LL_RES := 'application/scvp-vp-response';
        when '.scq' then
          LL_RES := 'application/scvp-cv-request';
        when '.scs' then
          LL_RES := 'application/scvp-cv-response';
        when '.sdp' then
          LL_RES := 'application/sdp';
        when '.etx' then
          LL_RES := 'text/x-setext';
        when '.movie' then
          LL_RES := 'video/x-sgi-movie';
        when '.ifm' then
          LL_RES := 'application/vnd.shana.informed.formdata';
        when '.itp' then
          LL_RES := 'application/vnd.shana.informed.formtemplate';
        when '.iif' then
          LL_RES := 'application/vnd.shana.informed.interchange';
        when '.ipk' then
          LL_RES := 'application/vnd.shana.informed.package';
        when '.tfi' then
          LL_RES := 'application/thraud+xml';
        when '.shar' then
          LL_RES := 'application/x-shar';
        when '.rgb' then
          LL_RES := 'image/x-rgb';
        when '.slt' then
          LL_RES := 'application/vnd.epson.salt';
        when '.aso' then
          LL_RES := 'application/vnd.accpac.simply.aso';
        when '.imp' then
          LL_RES := 'application/vnd.accpac.simply.imp';
        when '.twd' then
          LL_RES := 'application/vnd.simtech-mindmapper';
        when '.csp' then
          LL_RES := 'application/vnd.commonspace';
        when '.saf' then
          LL_RES := 'application/vnd.yamaha.smaf-audio';
        when '.mmf' then
          LL_RES := 'application/vnd.smaf';
        when '.spf' then
          LL_RES := 'application/vnd.yamaha.smaf-phrase';
        when '.teacher' then
          LL_RES := 'application/vnd.smart.teacher';
        when '.svd' then
          LL_RES := 'application/vnd.svd';
        when '.rq' then
          LL_RES := 'application/sparql-query';
        when '.srx' then
          LL_RES := 'application/sparql-results+xml';
        when '.gram' then
          LL_RES := 'application/srgs';
        when '.grxml' then
          LL_RES := 'application/srgs+xml';
        when '.ssml' then
          LL_RES := 'application/ssml+xml';
        when '.skp' then
          LL_RES := 'application/vnd.koan';
        when '.sgml' then
          LL_RES := 'text/sgml';
        when '.sdc' then
          LL_RES := 'application/vnd.stardivision.calc';
        when '.sda' then
          LL_RES := 'application/vnd.stardivision.draw';
        when '.sdd' then
          LL_RES := 'application/vnd.stardivision.impress';
        when '.smf' then
          LL_RES := 'application/vnd.stardivision.math';
        when '.sdw' then
          LL_RES := 'application/vnd.stardivision.writer';
        when '.sgl' then
          LL_RES := 'application/vnd.stardivision.writer-global';
        when '.sm' then
          LL_RES := 'application/vnd.stepmania.stepchart';
        when '.sit' then
          LL_RES := 'application/x-stuffit';
        when '.sitx' then
          LL_RES := 'application/x-stuffitx';
        when '.sdkm' then
          LL_RES := 'application/vnd.solent.sdkm+xml';
        when '.xo' then
          LL_RES := 'application/vnd.olpc-sugar';
        when '.au' then
          LL_RES := 'audio/basic';
        when '.wqd' then
          LL_RES := 'application/vnd.wqd';
        when '.sis' then
          LL_RES := 'application/vnd.symbian.install';
        when '.smi' then
          LL_RES := 'application/smil+xml';
        when '.xsm' then
          LL_RES := 'application/vnd.syncml+xml';
        when '.bdm' then
          LL_RES := 'application/vnd.syncml.dm+wbxml';
        when '.xdm' then
          LL_RES := 'application/vnd.syncml.dm+xml';
        when '.sv4cpio' then
          LL_RES := 'application/x-sv4cpio';
        when '.sv4crc' then
          LL_RES := 'application/x-sv4crc';
        when '.sbml' then
          LL_RES := 'application/sbml+xml';
        when '.tsv' then
          LL_RES := 'text/tab-separated-values';
        when '.tiff' then
          LL_RES := 'image/tiff';
        when '.tao' then
          LL_RES := 'application/vnd.tao.intent-module-archive';
        when '.tar' then
          LL_RES := 'application/x-tar';
        when '.tcl' then
          LL_RES := 'application/x-tcl';
        when '.tex' then
          LL_RES := 'application/x-tex';
        when '.tfm' then
          LL_RES := 'application/x-tex-tfm';
        when '.tei' then
          LL_RES := 'application/tei+xml';
        when '.txt' then
          LL_RES := 'text/plain';
        when '.dxp' then
          LL_RES := 'application/vnd.spotfire.dxp';
        when '.sfs' then
          LL_RES := 'application/vnd.spotfire.sfs';
        when '.tsd' then
          LL_RES := 'application/timestamped-data';
        when '.tpt' then
          LL_RES := 'application/vnd.trid.tpt';
        when '.mxs' then
          LL_RES := 'application/vnd.triscape.mxs';
        when '.t' then
          LL_RES := 'text/troff';
        when '.tra' then
          LL_RES := 'application/vnd.trueapp';
        when '.ttf' then
          LL_RES := 'application/x-font-ttf';
        when '.ttl' then
          LL_RES := 'text/turtle';
        when '.umj' then
          LL_RES := 'application/vnd.umajin';
        when '.uoml' then
          LL_RES := 'application/vnd.uoml+xml';
        when '.unityweb' then
          LL_RES := 'application/vnd.unity';
        when '.ufd' then
          LL_RES := 'application/vnd.ufdl';
        when '.uri' then
          LL_RES := 'text/uri-list';
        when '.utz' then
          LL_RES := 'application/vnd.uiq.theme';
        when '.ustar' then
          LL_RES := 'application/x-ustar';
        when '.uu' then
          LL_RES := 'text/x-uuencode';
        when '.vcs' then
          LL_RES := 'text/x-vcalendar';
        when '.vcf' then
          LL_RES := 'text/x-vcard';
        when '.vcd' then
          LL_RES := 'application/x-cdlink';
        when '.vsf' then
          LL_RES := 'application/vnd.vsf';
        when '.wrl' then
          LL_RES := 'model/vrml';
        when '.vcx' then
          LL_RES := 'application/vnd.vcx';
        when '.mts' then
          LL_RES := 'model/vnd.mts';
        when '.vtu' then
          LL_RES := 'model/vnd.vtu';
        when '.vis' then
          LL_RES := 'application/vnd.visionary';
        when '.viv' then
          LL_RES := 'video/vnd.vivo';
        when '.ccxml' then
          LL_RES := 'application/ccxml+xml,';
        when '.vxml' then
          LL_RES := 'application/voicexml+xml';
        when '.src' then
          LL_RES := 'application/x-wais-source';
        when '.wbxml' then
          LL_RES := 'application/vnd.wap.wbxml';
        when '.wbmp' then
          LL_RES := 'image/vnd.wap.wbmp';
        when '.wav' then
          LL_RES := 'audio/x-wav';
        when '.davmount' then
          LL_RES := 'application/davmount+xml';
        when '.woff' then
          LL_RES := 'application/x-font-woff';
        when '.wspolicy' then
          LL_RES := 'application/wspolicy+xml';
        when '.webp' then
          LL_RES := 'image/webp';
        when '.wtb' then
          LL_RES := 'application/vnd.webturbo';
        when '.wgt' then
          LL_RES := 'application/widget';
        when '.hlp' then
          LL_RES := 'application/winhlp';
        when '.wml' then
          LL_RES := 'text/vnd.wap.wml';
        when '.wmls' then
          LL_RES := 'text/vnd.wap.wmlscript';
        when '.wmlsc' then
          LL_RES := 'application/vnd.wap.wmlscriptc';
        when '.wpd' then
          LL_RES := 'application/vnd.wordperfect';
        when '.stf' then
          LL_RES := 'application/vnd.wt.stf';
        when '.wsdl' then
          LL_RES := 'application/wsdl+xml';
        when '.xbm' then
          LL_RES := 'image/x-xbitmap';
        when '.xpm' then
          LL_RES := 'image/x-xpixmap';
        when '.xwd' then
          LL_RES := 'image/x-xwindowdump';
        when '.der' then
          LL_RES := 'application/x-x509-ca-cert';
        when '.fig' then
          LL_RES := 'application/x-xfig';
        when '.xhtml' then
          LL_RES := 'application/xhtml+xml';
        when '.xml' then
          LL_RES := 'application/xml';
        when '.xdf' then
          LL_RES := 'application/xcap-diff+xml';
        when '.xenc' then
          LL_RES := 'application/xenc+xml';
        when '.xer' then
          LL_RES := 'application/patch-ops-error+xml';
        when '.rl' then
          LL_RES := 'application/resource-lists+xml';
        when '.rs' then
          LL_RES := 'application/rls-services+xml';
        when '.rld' then
          LL_RES := 'application/resource-lists-diff+xml';
        when '.xslt' then
          LL_RES := 'application/xslt+xml';
        when '.xop' then
          LL_RES := 'application/xop+xml';
        when '.xpi' then
          LL_RES := 'application/x-xpinstall';
        when '.xspf' then
          LL_RES := 'application/xspf+xml';
        when '.xul' then
          LL_RES := 'application/vnd.mozilla.xul+xml';
        when '.xyz' then
          LL_RES := 'chemical/x-xyz';
        when '.yaml' then
          LL_RES := 'text/yaml';
        when '.yang' then
          LL_RES := 'application/yang';
        when '.yin' then
          LL_RES := 'application/yin+xml';
        when '.zir' then
          LL_RES := 'application/vnd.zul';
        when '.zip' then
          LL_RES := 'application/zip';
        when '.zmm' then
          LL_RES := 'application/vnd.handheld-entertainment+xml';
        when '.zaz' then
          LL_RES := 'application/vnd.zzazz.deck+xml';
        else
          LL_RES := 'application/octet-stream';
      end case;
      return LL_RES;
    end;

/
