--------------------------------------------------------
--  File created - среда-мая-13-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDO_COND_STORE
--------------------------------------------------------

  CREATE TABLE "PARUS"."UDO_COND_STORE" 
   (	"RN" NUMBER(17,0), 
	"COND_GROUP" VARCHAR2(40 BYTE), 
	"STORE_NAME" VARCHAR2(160 BYTE), 
	"AUTHID" VARCHAR2(30 BYTE), 
	"ROLE" NUMBER(17,0), 
	"XVALUES" "PARUS"."XMLTYPE"
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USER_DATA" 
 XMLTYPE COLUMN "XVALUES" STORE AS CLOB (
  TABLESPACE "USER_DATA" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
 

   COMMENT ON COLUMN "PARUS"."UDO_COND_STORE"."COND_GROUP" IS 'Группа условий отбора';
 
   COMMENT ON COLUMN "PARUS"."UDO_COND_STORE"."STORE_NAME" IS 'Наименование хранимых условий';
 
   COMMENT ON COLUMN "PARUS"."UDO_COND_STORE"."AUTHID" IS 'Пользователь (ссылка на USERLIST.AUTHID)';
 
   COMMENT ON COLUMN "PARUS"."UDO_COND_STORE"."ROLE" IS 'Роль (ссылка на ROLES.RN))';
 
   COMMENT ON COLUMN "PARUS"."UDO_COND_STORE"."XVALUES" IS 'Условия';
--------------------------------------------------------
--  DDL for Index UDO_COND_STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARUS"."UDO_COND_STORE_PK" ON "PARUS"."UDO_COND_STORE" ("RN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USER_DATA" ;
--------------------------------------------------------
--  DDL for Index UDO_COND_STORE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARUS"."UDO_COND_STORE_UK" ON "PARUS"."UDO_COND_STORE" ("COND_GROUP", "AUTHID", "STORE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USER_DATA" ;
--------------------------------------------------------
--  DDL for Index I_UDO_COND_STORE_ROLE
--------------------------------------------------------

  CREATE INDEX "PARUS"."I_UDO_COND_STORE_ROLE" ON "PARUS"."UDO_COND_STORE" ("COND_GROUP", "ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USER_DATA" ;
--------------------------------------------------------
--  Ref Constraints for Table UDO_COND_STORE
--------------------------------------------------------

  ALTER TABLE "PARUS"."UDO_COND_STORE" ADD CONSTRAINT "UDO_COND_STORE_AUTH_FK" FOREIGN KEY ("AUTHID")
	  REFERENCES "PARUS"."USERLIST" ("AUTHID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "PARUS"."UDO_COND_STORE" ADD CONSTRAINT "UDO_COND_STORE_ROLE_FK" FOREIGN KEY ("ROLE")
	  REFERENCES "PARUS"."ROLES" ("RN") ON DELETE CASCADE ENABLE;
