CREATE OR REPLACE FUNCTION UDO_GET_FILE_CONTENTTYPE(
    fileName VARCHAR2 )
  RETURN VARCHAR2
IS
  contentType VARCHAR2( 1000 );
BEGIN
  CASE SUBSTR( fileName, instr( fileName, '.', - 1 ) )
  WHEN '.x3d' THEN
    contentType := 'application/vnd.hzn-3d-crossword';
  WHEN '.3gp' THEN
    contentType := 'video/3gpp';
  WHEN '.3g2' THEN
    contentType := 'video/3gpp2';
  WHEN '.mseq' THEN
    contentType := 'application/vnd.mseq';
  WHEN '.pwn' THEN
    contentType := 'application/vnd.3m.post-it-notes';
  WHEN '.plb' THEN
    contentType := 'application/vnd.3gpp.pic-bw-large';
  WHEN '.psb' THEN
    contentType := 'application/vnd.3gpp.pic-bw-small';
  WHEN '.pvb' THEN
    contentType := 'application/vnd.3gpp.pic-bw-var';
  WHEN '.tcap' THEN
    contentType := 'application/vnd.3gpp2.tcap';
  WHEN '.7z' THEN
    contentType := 'application/x-7z-compressed';
  WHEN '.abw' THEN
    contentType := 'application/x-abiword';
  WHEN '.ace' THEN
    contentType := 'application/x-ace-compressed';
  WHEN '.acc' THEN
    contentType := 'application/vnd.americandynamics.acc';
  WHEN '.acu' THEN
    contentType := 'application/vnd.acucobol';
  WHEN '.atc' THEN
    contentType := 'application/vnd.acucorp';
  WHEN '.adp' THEN
    contentType := 'audio/adpcm';
  WHEN '.aab' THEN
    contentType := 'application/x-authorware-bin';
  WHEN '.aam' THEN
    contentType := 'application/x-authorware-map';
  WHEN '.aas' THEN
    contentType := 'application/x-authorware-seg';
  WHEN '.air' THEN
    contentType := 'application/vnd.adobe.air-application-installer-package+zip';
  WHEN '.swf' THEN
    contentType := 'application/x-shockwave-flash';
  WHEN '.fxp' THEN
    contentType := 'application/vnd.adobe.fxp';
  WHEN '.pdf' THEN
    contentType := 'application/pdf';
  WHEN '.ppd' THEN
    contentType := 'application/vnd.cups-ppd';
  WHEN '.dir' THEN
    contentType := 'application/x-director';
  WHEN '.xdp' THEN
    contentType := 'application/vnd.adobe.xdp+xml';
  WHEN '.xfdf' THEN
    contentType := 'application/vnd.adobe.xfdf';
  WHEN '.aac' THEN
    contentType := 'audio/x-aac';
  WHEN '.ahead' THEN
    contentType := 'application/vnd.ahead.space';
  WHEN '.azf' THEN
    contentType := 'application/vnd.airzip.filesecure.azf';
  WHEN '.azs' THEN
    contentType := 'application/vnd.airzip.filesecure.azs';
  WHEN '.azw' THEN
    contentType := 'application/vnd.amazon.ebook';
  WHEN '.ami' THEN
    contentType := 'application/vnd.amiga.ami';
  WHEN 'N/A' THEN
    contentType := 'application/andrew-inset';
  WHEN '.apk' THEN
    contentType := 'application/vnd.android.package-archive';
  WHEN '.cii' THEN
    contentType := 'application/vnd.anser-web-certificate-issue-initiation';
  WHEN '.fti' THEN
    contentType := 'application/vnd.anser-web-funds-transfer-initiation';
  WHEN '.atx' THEN
    contentType := 'application/vnd.antix.game-component';
  WHEN '.mpkg' THEN
    contentType := 'application/vnd.apple.installer+xml';
  WHEN '.aw' THEN
    contentType := 'application/applixware';
  WHEN '.les' THEN
    contentType := 'application/vnd.hhe.lesson-player';
  WHEN '.swi' THEN
    contentType := 'application/vnd.aristanetworks.swi';
  WHEN '.s' THEN
    contentType := 'text/x-asm';
  WHEN '.atomcat' THEN
    contentType := 'application/atomcat+xml';
  WHEN '.atomsvc' THEN
    contentType := 'application/atomsvc+xml';
  WHEN '.atom, .xml' THEN
    contentType := 'application/atom+xml';
  WHEN '.ac' THEN
    contentType := 'application/pkix-attr-cert';
  WHEN '.aif' THEN
    contentType := 'audio/x-aiff';
  WHEN '.avi' THEN
    contentType := 'video/x-msvideo';
  WHEN '.aep' THEN
    contentType := 'application/vnd.audiograph';
  WHEN '.dxf' THEN
    contentType := 'image/vnd.dxf';
  WHEN '.dwf' THEN
    contentType := 'model/vnd.dwf';
  WHEN '.par' THEN
    contentType := 'text/plain-bas';
  WHEN '.bcpio' THEN
    contentType := 'application/x-bcpio';
  WHEN '.bin' THEN
    contentType := 'application/octet-stream';
  WHEN '.bmp' THEN
    contentType := 'image/bmp';
  WHEN '.torrent' THEN
    contentType := 'application/x-bittorrent';
  WHEN '.cod' THEN
    contentType := 'application/vnd.rim.cod';
  WHEN '.mpm' THEN
    contentType := 'application/vnd.blueice.multipass';
  WHEN '.bmi' THEN
    contentType := 'application/vnd.bmi';
  WHEN '.sh' THEN
    contentType := 'application/x-sh';
  WHEN '.btif' THEN
    contentType := 'image/prs.btif';
  WHEN '.rep' THEN
    contentType := 'application/vnd.businessobjects';
  WHEN '.bz' THEN
    contentType := 'application/x-bzip';
  WHEN '.bz2' THEN
    contentType := 'application/x-bzip2';
  WHEN '.csh' THEN
    contentType := 'application/x-csh';
  WHEN '.c' THEN
    contentType := 'text/x-c';
  WHEN '.cdxml' THEN
    contentType := 'application/vnd.chemdraw+xml';
  WHEN '.css' THEN
    contentType := 'text/css';
  WHEN '.cdx' THEN
    contentType := 'chemical/x-cdx';
  WHEN '.cml' THEN
    contentType := 'chemical/x-cml';
  WHEN '.csml' THEN
    contentType := 'chemical/x-csml';
  WHEN '.cdbcmsg' THEN
    contentType := 'application/vnd.contact.cmsg';
  WHEN '.cla' THEN
    contentType := 'application/vnd.claymore';
  WHEN '.c4g' THEN
    contentType := 'application/vnd.clonk.c4group';
  WHEN '.sub' THEN
    contentType := 'image/vnd.dvb.subtitle';
  WHEN '.cdmia' THEN
    contentType := 'application/cdmi-capability';
  WHEN '.cdmic' THEN
    contentType := 'application/cdmi-container';
  WHEN '.cdmid' THEN
    contentType := 'application/cdmi-domain';
  WHEN '.cdmio' THEN
    contentType := 'application/cdmi-object';
  WHEN '.cdmiq' THEN
    contentType := 'application/cdmi-queue';
  WHEN '.c11amc' THEN
    contentType := 'application/vnd.cluetrust.cartomobile-config';
  WHEN '.c11amz' THEN
    contentType := 'application/vnd.cluetrust.cartomobile-config-pkg';
  WHEN '.ras' THEN
    contentType := 'image/x-cmu-raster';
  WHEN '.dae' THEN
    contentType := 'model/vnd.collada+xml';
  WHEN '.csv' THEN
    contentType := 'text/csv';
  WHEN '.cpt' THEN
    contentType := 'application/mac-compactpro';
  WHEN '.wmlc' THEN
    contentType := 'application/vnd.wap.wmlc';
  WHEN '.cgm' THEN
    contentType := 'image/cgm';
  WHEN '.ice' THEN
    contentType := 'x-conference/x-cooltalk';
  WHEN '.cmx' THEN
    contentType := 'image/x-cmx';
  WHEN '.xar' THEN
    contentType := 'application/vnd.xara';
  WHEN '.cmc' THEN
    contentType := 'application/vnd.cosmocaller';
  WHEN '.cpio' THEN
    contentType := 'application/x-cpio';
  WHEN '.clkx' THEN
    contentType := 'application/vnd.crick.clicker';
  WHEN '.clkk' THEN
    contentType := 'application/vnd.crick.clicker.keyboard';
  WHEN '.clkp' THEN
    contentType := 'application/vnd.crick.clicker.palette';
  WHEN '.clkt' THEN
    contentType := 'application/vnd.crick.clicker.template';
  WHEN '.clkw' THEN
    contentType := 'application/vnd.crick.clicker.wordbank';
  WHEN '.wbs' THEN
    contentType := 'application/vnd.criticaltools.wbs+xml';
  WHEN '.cryptonote' THEN
    contentType := 'application/vnd.rig.cryptonote';
  WHEN '.cif' THEN
    contentType := 'chemical/x-cif';
  WHEN '.cmdf' THEN
    contentType := 'chemical/x-cmdf';
  WHEN '.cu' THEN
    contentType := 'application/cu-seeme';
  WHEN '.cww' THEN
    contentType := 'application/prs.cww';
  WHEN '.curl' THEN
    contentType := 'text/vnd.curl';
  WHEN '.dcurl' THEN
    contentType := 'text/vnd.curl.dcurl';
  WHEN '.mcurl' THEN
    contentType := 'text/vnd.curl.mcurl';
  WHEN '.scurl' THEN
    contentType := 'text/vnd.curl.scurl';
  WHEN '.car' THEN
    contentType := 'application/vnd.curl.car';
  WHEN '.pcurl' THEN
    contentType := 'application/vnd.curl.pcurl';
  WHEN '.cmp' THEN
    contentType := 'application/vnd.yellowriver-custom-menu';
  WHEN '.dssc' THEN
    contentType := 'application/dssc+der';
  WHEN '.xdssc' THEN
    contentType := 'application/dssc+xml';
  WHEN '.deb' THEN
    contentType := 'application/x-debian-package';
  WHEN '.uva' THEN
    contentType := 'audio/vnd.dece.audio';
  WHEN '.uvi' THEN
    contentType := 'image/vnd.dece.graphic';
  WHEN '.uvh' THEN
    contentType := 'video/vnd.dece.hd';
  WHEN '.uvm' THEN
    contentType := 'video/vnd.dece.mobile';
  WHEN '.uvu' THEN
    contentType := 'video/vnd.uvvu.mp4';
  WHEN '.uvp' THEN
    contentType := 'video/vnd.dece.pd';
  WHEN '.uvs' THEN
    contentType := 'video/vnd.dece.sd';
  WHEN '.uvv' THEN
    contentType := 'video/vnd.dece.video';
  WHEN '.dvi' THEN
    contentType := 'application/x-dvi';
  WHEN '.seed' THEN
    contentType := 'application/vnd.fdsn.seed';
  WHEN '.dtb' THEN
    contentType := 'application/x-dtbook+xml';
  WHEN '.res' THEN
    contentType := 'application/x-dtbresource+xml';
  WHEN '.ait' THEN
    contentType := 'application/vnd.dvb.ait';
  WHEN '.svc' THEN
    contentType := 'application/vnd.dvb.service';
  WHEN '.eol' THEN
    contentType := 'audio/vnd.digital-winds';
  WHEN '.djvu' THEN
    contentType := 'image/vnd.djvu';
  WHEN '.dtd' THEN
    contentType := 'application/xml-dtd';
  WHEN '.mlp' THEN
    contentType := 'application/vnd.dolby.mlp';
  WHEN '.wad' THEN
    contentType := 'application/x-doom';
  WHEN '.dpg' THEN
    contentType := 'application/vnd.dpgraph';
  WHEN '.dra' THEN
    contentType := 'audio/vnd.dra';
  WHEN '.dfac' THEN
    contentType := 'application/vnd.dreamfactory';
  WHEN '.dts' THEN
    contentType := 'audio/vnd.dts';
  WHEN '.dtshd' THEN
    contentType := 'audio/vnd.dts.hd';
  WHEN '.dwg' THEN
    contentType := 'image/vnd.dwg';
  WHEN '.geo' THEN
    contentType := 'application/vnd.dynageo';
  WHEN '.es' THEN
    contentType := 'application/ecmascript';
  WHEN '.mag' THEN
    contentType := 'application/vnd.ecowin.chart';
  WHEN '.mmr' THEN
    contentType := 'image/vnd.fujixerox.edmics-mmr';
  WHEN '.rlc' THEN
    contentType := 'image/vnd.fujixerox.edmics-rlc';
  WHEN '.exi' THEN
    contentType := 'application/exi';
  WHEN '.mgz' THEN
    contentType := 'application/vnd.proteus.magazine';
  WHEN '.epub' THEN
    contentType := 'application/epub+zip';
  WHEN '.eml' THEN
    contentType := 'message/rfc822';
  WHEN '.nml' THEN
    contentType := 'application/vnd.enliven';
  WHEN '.xpr' THEN
    contentType := 'application/vnd.is-xpr';
  WHEN '.xif' THEN
    contentType := 'image/vnd.xiff';
  WHEN '.xfdl' THEN
    contentType := 'application/vnd.xfdl';
  WHEN '.emma' THEN
    contentType := 'application/emma+xml';
  WHEN '.ez2' THEN
    contentType := 'application/vnd.ezpix-album';
  WHEN '.ez3' THEN
    contentType := 'application/vnd.ezpix-package';
  WHEN '.fst' THEN
    contentType := 'image/vnd.fst';
  WHEN '.fvt' THEN
    contentType := 'video/vnd.fvt';
  WHEN '.fbs' THEN
    contentType := 'image/vnd.fastbidsheet';
  WHEN '.fe_launch' THEN
    contentType := 'application/vnd.denovo.fcselayout-link';
  WHEN '.f4v' THEN
    contentType := 'video/x-f4v';
  WHEN '.flv' THEN
    contentType := 'video/x-flv';
  WHEN '.fpx' THEN
    contentType := 'image/vnd.fpx';
  WHEN '.npx' THEN
    contentType := 'image/vnd.net-fpx';
  WHEN '.flx' THEN
    contentType := 'text/vnd.fmi.flexstor';
  WHEN '.fli' THEN
    contentType := 'video/x-fli';
  WHEN '.ftc' THEN
    contentType := 'application/vnd.fluxtime.clip';
  WHEN '.fdf' THEN
    contentType := 'application/vnd.fdf';
  WHEN '.f' THEN
    contentType := 'text/x-fortran';
  WHEN '.mif' THEN
    contentType := 'application/vnd.mif';
  WHEN '.fm' THEN
    contentType := 'application/vnd.framemaker';
  WHEN '.fh' THEN
    contentType := 'image/x-freehand';
  WHEN '.fsc' THEN
    contentType := 'application/vnd.fsc.weblaunch';
  WHEN '.fnc' THEN
    contentType := 'application/vnd.frogans.fnc';
  WHEN '.ltf' THEN
    contentType := 'application/vnd.frogans.ltf';
  WHEN '.ddd' THEN
    contentType := 'application/vnd.fujixerox.ddd';
  WHEN '.xdw' THEN
    contentType := 'application/vnd.fujixerox.docuworks';
  WHEN '.xbd' THEN
    contentType := 'application/vnd.fujixerox.docuworks.binder';
  WHEN '.oas' THEN
    contentType := 'application/vnd.fujitsu.oasys';
  WHEN '.oa2' THEN
    contentType := 'application/vnd.fujitsu.oasys2';
  WHEN '.oa3' THEN
    contentType := 'application/vnd.fujitsu.oasys3';
  WHEN '.fg5' THEN
    contentType := 'application/vnd.fujitsu.oasysgp';
  WHEN '.bh2' THEN
    contentType := 'application/vnd.fujitsu.oasysprs';
  WHEN '.spl' THEN
    contentType := 'application/x-futuresplash';
  WHEN '.fzs' THEN
    contentType := 'application/vnd.fuzzysheet';
  WHEN '.g3' THEN
    contentType := 'image/g3fax';
  WHEN '.gmx' THEN
    contentType := 'application/vnd.gmx';
  WHEN '.gtw' THEN
    contentType := 'model/vnd.gtw';
  WHEN '.txd' THEN
    contentType := 'application/vnd.genomatix.tuxedo';
  WHEN '.ggb' THEN
    contentType := 'application/vnd.geogebra.file';
  WHEN '.ggt' THEN
    contentType := 'application/vnd.geogebra.tool';
  WHEN '.gdl' THEN
    contentType := 'model/vnd.gdl';
  WHEN '.gex' THEN
    contentType := 'application/vnd.geometry-explorer';
  WHEN '.gxt' THEN
    contentType := 'application/vnd.geonext';
  WHEN '.g2w' THEN
    contentType := 'application/vnd.geoplan';
  WHEN '.g3w' THEN
    contentType := 'application/vnd.geospace';
  WHEN '.gsf' THEN
    contentType := 'application/x-font-ghostscript';
  WHEN '.bdf' THEN
    contentType := 'application/x-font-bdf';
  WHEN '.gtar' THEN
    contentType := 'application/x-gtar';
  WHEN '.texinfo' THEN
    contentType := 'application/x-texinfo';
  WHEN '.gnumeric' THEN
    contentType := 'application/x-gnumeric';
  WHEN '.kml' THEN
    contentType := 'application/vnd.google-earth.kml+xml';
  WHEN '.kmz' THEN
    contentType := 'application/vnd.google-earth.kmz';
  WHEN '.gqf' THEN
    contentType := 'application/vnd.grafeq';
  WHEN '.gif' THEN
    contentType := 'image/gif';
  WHEN '.gv' THEN
    contentType := 'text/vnd.graphviz';
  WHEN '.gac' THEN
    contentType := 'application/vnd.groove-account';
  WHEN '.ghf' THEN
    contentType := 'application/vnd.groove-help';
  WHEN '.gim' THEN
    contentType := 'application/vnd.groove-identity-message';
  WHEN '.grv' THEN
    contentType := 'application/vnd.groove-injector';
  WHEN '.gtm' THEN
    contentType := 'application/vnd.groove-tool-message';
  WHEN '.tpl' THEN
    contentType := 'application/vnd.groove-tool-template';
  WHEN '.vcg' THEN
    contentType := 'application/vnd.groove-vcard';
  WHEN '.h261' THEN
    contentType := 'video/h261';
  WHEN '.h263' THEN
    contentType := 'video/h263';
  WHEN '.h264' THEN
    contentType := 'video/h264';
  WHEN '.hpid' THEN
    contentType := 'application/vnd.hp-hpid';
  WHEN '.hps' THEN
    contentType := 'application/vnd.hp-hps';
  WHEN '.hdf' THEN
    contentType := 'application/x-hdf';
  WHEN '.rip' THEN
    contentType := 'audio/vnd.rip';
  WHEN '.hbci' THEN
    contentType := 'application/vnd.hbci';
  WHEN '.jlt' THEN
    contentType := 'application/vnd.hp-jlyt';
  WHEN '.pcl' THEN
    contentType := 'application/vnd.hp-pcl';
  WHEN '.hpgl' THEN
    contentType := 'application/vnd.hp-hpgl';
  WHEN '.hvs' THEN
    contentType := 'application/vnd.yamaha.hv-script';
  WHEN '.hvd' THEN
    contentType := 'application/vnd.yamaha.hv-dic';
  WHEN '.hvp' THEN
    contentType := 'application/vnd.yamaha.hv-voice';
  WHEN '.sfd-hdstx' THEN
    contentType := 'application/vnd.hydrostatix.sof-data';
  WHEN '.stk' THEN
    contentType := 'application/hyperstudio';
  WHEN '.hal' THEN
    contentType := 'application/vnd.hal+xml';
  WHEN '.html' THEN
    contentType := 'text/html';
  WHEN '.irm' THEN
    contentType := 'application/vnd.ibm.rights-management';
  WHEN '.sc' THEN
    contentType := 'application/vnd.ibm.secure-container';
  WHEN '.ics' THEN
    contentType := 'text/calendar';
  WHEN '.icc' THEN
    contentType := 'application/vnd.iccprofile';
  WHEN '.ico' THEN
    contentType := 'image/x-icon';
  WHEN '.igl' THEN
    contentType := 'application/vnd.igloader';
  WHEN '.ief' THEN
    contentType := 'image/ief';
  WHEN '.ivp' THEN
    contentType := 'application/vnd.immervision-ivp';
  WHEN '.ivu' THEN
    contentType := 'application/vnd.immervision-ivu';
  WHEN '.rif' THEN
    contentType := 'application/reginfo+xml';
  WHEN '.3dml' THEN
    contentType := 'text/vnd.in3d.3dml';
  WHEN '.spot' THEN
    contentType := 'text/vnd.in3d.spot';
  WHEN '.igs' THEN
    contentType := 'model/iges';
  WHEN '.i2g' THEN
    contentType := 'application/vnd.intergeo';
  WHEN '.cdy' THEN
    contentType := 'application/vnd.cinderella';
  WHEN '.xpw' THEN
    contentType := 'application/vnd.intercon.formnet';
  WHEN '.fcs' THEN
    contentType := 'application/vnd.isac.fcs';
  WHEN '.ipfix' THEN
    contentType := 'application/ipfix';
  WHEN '.cer' THEN
    contentType := 'application/pkix-cert';
  WHEN '.pki' THEN
    contentType := 'application/pkixcmp';
  WHEN '.crl' THEN
    contentType := 'application/pkix-crl';
  WHEN '.pkipath' THEN
    contentType := 'application/pkix-pkipath';
  WHEN '.igm' THEN
    contentType := 'application/vnd.insors.igm';
  WHEN '.rcprofile' THEN
    contentType := 'application/vnd.ipunplugged.rcprofile';
  WHEN '.irp' THEN
    contentType := 'application/vnd.irepository.package+xml';
  WHEN '.jad' THEN
    contentType := 'text/vnd.sun.j2me.app-descriptor';
  WHEN '.jar' THEN
    contentType := 'application/java-archive';
  WHEN '.class' THEN
    contentType := 'application/java-vm';
  WHEN '.jnlp' THEN
    contentType := 'application/x-java-jnlp-file';
  WHEN '.ser' THEN
    contentType := 'application/java-serialized-object';
  WHEN '.java' THEN
    contentType := 'text/x-java-source,java';
  WHEN '.js' THEN
    contentType := 'application/javascript';
  WHEN '.json' THEN
    contentType := 'application/json';
  WHEN '.joda' THEN
    contentType := 'application/vnd.joost.joda-archive';
  WHEN '.jpm' THEN
    contentType := 'video/jpm';
  WHEN '.jpeg, .jpg' THEN
    contentType := 'image/jpeg';
  WHEN '.jpgv' THEN
    contentType := 'video/jpeg';
  WHEN '.ktz' THEN
    contentType := 'application/vnd.kahootz';
  WHEN '.mmd' THEN
    contentType := 'application/vnd.chipnuts.karaoke-mmd';
  WHEN '.karbon' THEN
    contentType := 'application/vnd.kde.karbon';
  WHEN '.chrt' THEN
    contentType := 'application/vnd.kde.kchart';
  WHEN '.kfo' THEN
    contentType := 'application/vnd.kde.kformula';
  WHEN '.flw' THEN
    contentType := 'application/vnd.kde.kivio';
  WHEN '.kon' THEN
    contentType := 'application/vnd.kde.kontour';
  WHEN '.kpr' THEN
    contentType := 'application/vnd.kde.kpresenter';
  WHEN '.ksp' THEN
    contentType := 'application/vnd.kde.kspread';
  WHEN '.kwd' THEN
    contentType := 'application/vnd.kde.kword';
  WHEN '.htke' THEN
    contentType := 'application/vnd.kenameaapp';
  WHEN '.kia' THEN
    contentType := 'application/vnd.kidspiration';
  WHEN '.kne' THEN
    contentType := 'application/vnd.kinar';
  WHEN '.sse' THEN
    contentType := 'application/vnd.kodak-descriptor';
  WHEN '.lasxml' THEN
    contentType := 'application/vnd.las.las+xml';
  WHEN '.latex' THEN
    contentType := 'application/x-latex';
  WHEN '.lbd' THEN
    contentType := 'application/vnd.llamagraphics.life-balance.desktop';
  WHEN '.lbe' THEN
    contentType := 'application/vnd.llamagraphics.life-balance.exchange+xml';
  WHEN '.jam' THEN
    contentType := 'application/vnd.jam';
  WHEN '.123' THEN
    contentType := 'application/vnd.lotus-1-2-3';
  WHEN '.apr' THEN
    contentType := 'application/vnd.lotus-approach';
  WHEN '.pre' THEN
    contentType := 'application/vnd.lotus-freelance';
  WHEN '.nsf' THEN
    contentType := 'application/vnd.lotus-notes';
  WHEN '.org' THEN
    contentType := 'application/vnd.lotus-organizer';
  WHEN '.scm' THEN
    contentType := 'application/vnd.lotus-screencam';
  WHEN '.lwp' THEN
    contentType := 'application/vnd.lotus-wordpro';
  WHEN '.lvp' THEN
    contentType := 'audio/vnd.lucent.voice';
  WHEN '.m3u' THEN
    contentType := 'audio/x-mpegurl';
  WHEN '.m4v' THEN
    contentType := 'video/x-m4v';
  WHEN '.hqx' THEN
    contentType := 'application/mac-binhex40';
  WHEN '.portpkg' THEN
    contentType := 'application/vnd.macports.portpkg';
  WHEN '.mgp' THEN
    contentType := 'application/vnd.osgeo.mapguide.package';
  WHEN '.mrc' THEN
    contentType := 'application/marc';
  WHEN '.mrcx' THEN
    contentType := 'application/marcxml+xml';
  WHEN '.mxf' THEN
    contentType := 'application/mxf';
  WHEN '.nbp' THEN
    contentType := 'application/vnd.wolfram.player';
  WHEN '.ma' THEN
    contentType := 'application/mathematica';
  WHEN '.mathml' THEN
    contentType := 'application/mathml+xml';
  WHEN '.mbox' THEN
    contentType := 'application/mbox';
  WHEN '.mc1' THEN
    contentType := 'application/vnd.medcalcdata';
  WHEN '.mscml' THEN
    contentType := 'application/mediaservercontrol+xml';
  WHEN '.cdkey' THEN
    contentType := 'application/vnd.mediastation.cdkey';
  WHEN '.mwf' THEN
    contentType := 'application/vnd.mfer';
  WHEN '.mfm' THEN
    contentType := 'application/vnd.mfmp';
  WHEN '.msh' THEN
    contentType := 'model/mesh';
  WHEN '.mads' THEN
    contentType := 'application/mads+xml';
  WHEN '.mets' THEN
    contentType := 'application/mets+xml';
  WHEN '.mods' THEN
    contentType := 'application/mods+xml';
  WHEN '.meta4' THEN
    contentType := 'application/metalink4+xml';
  WHEN '.potm' THEN
    contentType := 'application/vnd.ms-powerpoint.template.macroenabled.12';
  WHEN '.docm' THEN
    contentType := 'application/vnd.ms-word.document.macroenabled.12';
  WHEN '.dotm' THEN
    contentType := 'application/vnd.ms-word.template.macroenabled.12';
  WHEN '.mcd' THEN
    contentType := 'application/vnd.mcd';
  WHEN '.flo' THEN
    contentType := 'application/vnd.micrografx.flo';
  WHEN '.igx' THEN
    contentType := 'application/vnd.micrografx.igx';
  WHEN '.es3' THEN
    contentType := 'application/vnd.eszigno3+xml';
  WHEN '.mdb' THEN
    contentType := 'application/x-msaccess';
  WHEN '.asf' THEN
    contentType := 'video/x-ms-asf';
  WHEN '.exe' THEN
    contentType := 'application/x-msdownload';
  WHEN '.cil' THEN
    contentType := 'application/vnd.ms-artgalry';
  WHEN '.cab' THEN
    contentType := 'application/vnd.ms-cab-compressed';
  WHEN '.ims' THEN
    contentType := 'application/vnd.ms-ims';
  WHEN '.application' THEN
    contentType := 'application/x-ms-application';
  WHEN '.clp' THEN
    contentType := 'application/x-msclip';
  WHEN '.mdi' THEN
    contentType := 'image/vnd.ms-modi';
  WHEN '.eot' THEN
    contentType := 'application/vnd.ms-fontobject';
  WHEN '.xls' THEN
    contentType := 'application/vnd.ms-excel';
  WHEN '.xlam' THEN
    contentType := 'application/vnd.ms-excel.addin.macroenabled.12';
  WHEN '.xlsb' THEN
    contentType := 'application/vnd.ms-excel.sheet.binary.macroenabled.12';
  WHEN '.xltm' THEN
    contentType := 'application/vnd.ms-excel.template.macroenabled.12';
  WHEN '.xlsm' THEN
    contentType := 'application/vnd.ms-excel.sheet.macroenabled.12';
  WHEN '.chm' THEN
    contentType := 'application/vnd.ms-htmlhelp';
  WHEN '.crd' THEN
    contentType := 'application/x-mscardfile';
  WHEN '.lrm' THEN
    contentType := 'application/vnd.ms-lrm';
  WHEN '.mvb' THEN
    contentType := 'application/x-msmediaview';
  WHEN '.mny' THEN
    contentType := 'application/x-msmoney';
  WHEN '.pptx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
  WHEN '.sldx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.presentationml.slide';
  WHEN '.ppsx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.presentationml.slideshow';
  WHEN '.potx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.presentationml.template';
  WHEN '.xlsx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
  WHEN '.xltx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.spreadsheetml.template';
  WHEN '.docx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  WHEN '.dotx' THEN
    contentType := 'application/vnd.openxmlformats-officedocument.wordprocessingml.template';
  WHEN '.obd' THEN
    contentType := 'application/x-msbinder';
  WHEN '.thmx' THEN
    contentType := 'application/vnd.ms-officetheme';
  WHEN '.onetoc' THEN
    contentType := 'application/onenote';
  WHEN '.pya' THEN
    contentType := 'audio/vnd.ms-playready.media.pya';
  WHEN '.pyv' THEN
    contentType := 'video/vnd.ms-playready.media.pyv';
  WHEN '.ppt' THEN
    contentType := 'application/vnd.ms-powerpoint';
  WHEN '.ppam' THEN
    contentType := 'application/vnd.ms-powerpoint.addin.macroenabled.12';
  WHEN '.sldm' THEN
    contentType := 'application/vnd.ms-powerpoint.slide.macroenabled.12';
  WHEN '.pptm' THEN
    contentType := 'application/vnd.ms-powerpoint.presentation.macroenabled.12';
  WHEN '.ppsm' THEN
    contentType := 'application/vnd.ms-powerpoint.slideshow.macroenabled.12';
  WHEN '.mpp' THEN
    contentType := 'application/vnd.ms-project';
  WHEN '.pub' THEN
    contentType := 'application/x-mspublisher';
  WHEN '.scd' THEN
    contentType := 'application/x-msschedule';
  WHEN '.xap' THEN
    contentType := 'application/x-silverlight-app';
  WHEN '.stl' THEN
    contentType := 'application/vnd.ms-pki.stl';
  WHEN '.cat' THEN
    contentType := 'application/vnd.ms-pki.seccat';
  WHEN '.vsd' THEN
    contentType := 'application/vnd.visio';
  WHEN '.wm' THEN
    contentType := 'video/x-ms-wm';
  WHEN '.wma' THEN
    contentType := 'audio/x-ms-wma';
  WHEN '.wax' THEN
    contentType := 'audio/x-ms-wax';
  WHEN '.wmx' THEN
    contentType := 'video/x-ms-wmx';
  WHEN '.wmd' THEN
    contentType := 'application/x-ms-wmd';
  WHEN '.wpl' THEN
    contentType := 'application/vnd.ms-wpl';
  WHEN '.wmz' THEN
    contentType := 'application/x-ms-wmz';
  WHEN '.wmv' THEN
    contentType := 'video/x-ms-wmv';
  WHEN '.wvx' THEN
    contentType := 'video/x-ms-wvx';
  WHEN '.wmf' THEN
    contentType := 'application/x-msmetafile';
  WHEN '.trm' THEN
    contentType := 'application/x-msterminal';
  WHEN '.doc' THEN
    contentType := 'application/msword';
  WHEN '.wri' THEN
    contentType := 'application/x-mswrite';
  WHEN '.wps' THEN
    contentType := 'application/vnd.ms-works';
  WHEN '.xbap' THEN
    contentType := 'application/x-ms-xbap';
  WHEN '.xps' THEN
    contentType := 'application/vnd.ms-xpsdocument';
  WHEN '.mid' THEN
    contentType := 'audio/midi';
  WHEN '.mpy' THEN
    contentType := 'application/vnd.ibm.minipay';
  WHEN '.afp' THEN
    contentType := 'application/vnd.ibm.modcap';
  WHEN '.rms' THEN
    contentType := 'application/vnd.jcp.javame.midlet-rms';
  WHEN '.tmo' THEN
    contentType := 'application/vnd.tmobile-livetv';
  WHEN '.prc' THEN
    contentType := 'application/x-mobipocket-ebook';
  WHEN '.mbk' THEN
    contentType := 'application/vnd.mobius.mbk';
  WHEN '.dis' THEN
    contentType := 'application/vnd.mobius.dis';
  WHEN '.plc' THEN
    contentType := 'application/vnd.mobius.plc';
  WHEN '.mqy' THEN
    contentType := 'application/vnd.mobius.mqy';
  WHEN '.msl' THEN
    contentType := 'application/vnd.mobius.msl';
  WHEN '.txf' THEN
    contentType := 'application/vnd.mobius.txf';
  WHEN '.daf' THEN
    contentType := 'application/vnd.mobius.daf';
  WHEN '.fly' THEN
    contentType := 'text/vnd.fly';
  WHEN '.mpc' THEN
    contentType := 'application/vnd.mophun.certificate';
  WHEN '.mpn' THEN
    contentType := 'application/vnd.mophun.application';
  WHEN '.mj2' THEN
    contentType := 'video/mj2';
  WHEN '.mpga' THEN
    contentType := 'audio/mpeg';
  WHEN '.mxu' THEN
    contentType := 'video/vnd.mpegurl';
  WHEN '.mpeg' THEN
    contentType := 'video/mpeg';
  WHEN '.m21' THEN
    contentType := 'application/mp21';
  WHEN '.mp4a' THEN
    contentType := 'audio/mp4';
  WHEN '.mp4' THEN
    contentType := 'video/mp4';
  WHEN '.mp4' THEN
    contentType := 'application/mp4';
  WHEN '.m3u8' THEN
    contentType := 'application/vnd.apple.mpegurl';
  WHEN '.mus' THEN
    contentType := 'application/vnd.musician';
  WHEN '.msty' THEN
    contentType := 'application/vnd.muvee.style';
  WHEN '.mxml' THEN
    contentType := 'application/xv+xml';
  WHEN '.ngdat' THEN
    contentType := 'application/vnd.nokia.n-gage.data';
  WHEN '.n-gage' THEN
    contentType := 'application/vnd.nokia.n-gage.symbian.install';
  WHEN '.ncx' THEN
    contentType := 'application/x-dtbncx+xml';
  WHEN '.nc' THEN
    contentType := 'application/x-netcdf';
  WHEN '.nlu' THEN
    contentType := 'application/vnd.neurolanguage.nlu';
  WHEN '.dna' THEN
    contentType := 'application/vnd.dna';
  WHEN '.nnd' THEN
    contentType := 'application/vnd.noblenet-directory';
  WHEN '.nns' THEN
    contentType := 'application/vnd.noblenet-sealer';
  WHEN '.nnw' THEN
    contentType := 'application/vnd.noblenet-web';
  WHEN '.rpst' THEN
    contentType := 'application/vnd.nokia.radio-preset';
  WHEN '.rpss' THEN
    contentType := 'application/vnd.nokia.radio-presets';
  WHEN '.n3' THEN
    contentType := 'text/n3';
  WHEN '.edm' THEN
    contentType := 'application/vnd.novadigm.edm';
  WHEN '.edx' THEN
    contentType := 'application/vnd.novadigm.edx';
  WHEN '.ext' THEN
    contentType := 'application/vnd.novadigm.ext';
  WHEN '.gph' THEN
    contentType := 'application/vnd.flographit';
  WHEN '.ecelp4800' THEN
    contentType := 'audio/vnd.nuera.ecelp4800';
  WHEN '.ecelp7470' THEN
    contentType := 'audio/vnd.nuera.ecelp7470';
  WHEN '.ecelp9600' THEN
    contentType := 'audio/vnd.nuera.ecelp9600';
  WHEN '.oda' THEN
    contentType := 'application/oda';
  WHEN '.ogx' THEN
    contentType := 'application/ogg';
  WHEN '.oga' THEN
    contentType := 'audio/ogg';
  WHEN '.ogv' THEN
    contentType := 'video/ogg';
  WHEN '.dd2' THEN
    contentType := 'application/vnd.oma.dd2+xml';
  WHEN '.oth' THEN
    contentType := 'application/vnd.oasis.opendocument.text-web';
  WHEN '.opf' THEN
    contentType := 'application/oebps-package+xml';
  WHEN '.qbo' THEN
    contentType := 'application/vnd.intu.qbo';
  WHEN '.oxt' THEN
    contentType := 'application/vnd.openofficeorg.extension';
  WHEN '.osf' THEN
    contentType := 'application/vnd.yamaha.openscoreformat';
  WHEN '.weba' THEN
    contentType := 'audio/webm';
  WHEN '.webm' THEN
    contentType := 'video/webm';
  WHEN '.odc' THEN
    contentType := 'application/vnd.oasis.opendocument.chart';
  WHEN '.otc' THEN
    contentType := 'application/vnd.oasis.opendocument.chart-template';
  WHEN '.odb' THEN
    contentType := 'application/vnd.oasis.opendocument.database';
  WHEN '.odf' THEN
    contentType := 'application/vnd.oasis.opendocument.formula';
  WHEN '.odft' THEN
    contentType := 'application/vnd.oasis.opendocument.formula-template';
  WHEN '.odg' THEN
    contentType := 'application/vnd.oasis.opendocument.graphics';
  WHEN '.otg' THEN
    contentType := 'application/vnd.oasis.opendocument.graphics-template';
  WHEN '.odi' THEN
    contentType := 'application/vnd.oasis.opendocument.image';
  WHEN '.oti' THEN
    contentType := 'application/vnd.oasis.opendocument.image-template';
  WHEN '.odp' THEN
    contentType := 'application/vnd.oasis.opendocument.presentation';
  WHEN '.otp' THEN
    contentType := 'application/vnd.oasis.opendocument.presentation-template';
  WHEN '.ods' THEN
    contentType := 'application/vnd.oasis.opendocument.spreadsheet';
  WHEN '.ots' THEN
    contentType := 'application/vnd.oasis.opendocument.spreadsheet-template';
  WHEN '.odt' THEN
    contentType := 'application/vnd.oasis.opendocument.text';
  WHEN '.odm' THEN
    contentType := 'application/vnd.oasis.opendocument.text-master';
  WHEN '.ott' THEN
    contentType := 'application/vnd.oasis.opendocument.text-template';
  WHEN '.ktx' THEN
    contentType := 'image/ktx';
  WHEN '.sxc' THEN
    contentType := 'application/vnd.sun.xml.calc';
  WHEN '.stc' THEN
    contentType := 'application/vnd.sun.xml.calc.template';
  WHEN '.sxd' THEN
    contentType := 'application/vnd.sun.xml.draw';
  WHEN '.std' THEN
    contentType := 'application/vnd.sun.xml.draw.template';
  WHEN '.sxi' THEN
    contentType := 'application/vnd.sun.xml.impress';
  WHEN '.sti' THEN
    contentType := 'application/vnd.sun.xml.impress.template';
  WHEN '.sxm' THEN
    contentType := 'application/vnd.sun.xml.math';
  WHEN '.sxw' THEN
    contentType := 'application/vnd.sun.xml.writer';
  WHEN '.sxg' THEN
    contentType := 'application/vnd.sun.xml.writer.global';
  WHEN '.stw' THEN
    contentType := 'application/vnd.sun.xml.writer.template';
  WHEN '.otf' THEN
    contentType := 'application/x-font-otf';
  WHEN '.osfpvg' THEN
    contentType := 'application/vnd.yamaha.openscoreformat.osfpvg+xml';
  WHEN '.dp' THEN
    contentType := 'application/vnd.osgi.dp';
  WHEN '.pdb' THEN
    contentType := 'application/vnd.palm';
  WHEN '.p' THEN
    contentType := 'text/x-pascal';
  WHEN '.paw' THEN
    contentType := 'application/vnd.pawaafile';
  WHEN '.pclxl' THEN
    contentType := 'application/vnd.hp-pclxl';
  WHEN '.efif' THEN
    contentType := 'application/vnd.picsel';
  WHEN '.pcx' THEN
    contentType := 'image/x-pcx';
  WHEN '.psd' THEN
    contentType := 'image/vnd.adobe.photoshop';
  WHEN '.prf' THEN
    contentType := 'application/pics-rules';
  WHEN '.pic' THEN
    contentType := 'image/x-pict';
  WHEN '.chat' THEN
    contentType := 'application/x-chat';
  WHEN '.p10' THEN
    contentType := 'application/pkcs10';
  WHEN '.p12' THEN
    contentType := 'application/x-pkcs12';
  WHEN '.p7m' THEN
    contentType := 'application/pkcs7-mime';
  WHEN '.p7s' THEN
    contentType := 'application/pkcs7-signature';
  WHEN '.p7r' THEN
    contentType := 'application/x-pkcs7-certreqresp';
  WHEN '.p7b' THEN
    contentType := 'application/x-pkcs7-certificates';
  WHEN '.p8' THEN
    contentType := 'application/pkcs8';
  WHEN '.plf' THEN
    contentType := 'application/vnd.pocketlearn';
  WHEN '.pnm' THEN
    contentType := 'image/x-portable-anymap';
  WHEN '.pbm' THEN
    contentType := 'image/x-portable-bitmap';
  WHEN '.pcf' THEN
    contentType := 'application/x-font-pcf';
  WHEN '.pfr' THEN
    contentType := 'application/font-tdpfr';
  WHEN '.pgn' THEN
    contentType := 'application/x-chess-pgn';
  WHEN '.pgm' THEN
    contentType := 'image/x-portable-graymap';
  WHEN '.png' THEN
    contentType := 'image/png';
  WHEN '.ppm' THEN
    contentType := 'image/x-portable-pixmap';
  WHEN '.pskcxml' THEN
    contentType := 'application/pskc+xml';
  WHEN '.pml' THEN
    contentType := 'application/vnd.ctc-posml';
  WHEN '.ai' THEN
    contentType := 'application/postscript';
  WHEN '.pfa' THEN
    contentType := 'application/x-font-type1';
  WHEN '.pbd' THEN
    contentType := 'application/vnd.powerbuilder6';
  WHEN '.box' THEN
    contentType := 'application/vnd.previewsystems.box';
  WHEN '.ptid' THEN
    contentType := 'application/vnd.pvi.ptid1';
  WHEN '.pls' THEN
    contentType := 'application/pls+xml';
  WHEN '.str' THEN
    contentType := 'application/vnd.pg.format';
  WHEN '.ei6' THEN
    contentType := 'application/vnd.pg.osasli';
  WHEN '.dsc' THEN
    contentType := 'text/prs.lines.tag';
  WHEN '.psf' THEN
    contentType := 'application/x-font-linux-psf';
  WHEN '.qps' THEN
    contentType := 'application/vnd.publishare-delta-tree';
  WHEN '.wg' THEN
    contentType := 'application/vnd.pmi.widget';
  WHEN '.qxd' THEN
    contentType := 'application/vnd.quark.quarkxpress';
  WHEN '.esf' THEN
    contentType := 'application/vnd.epson.esf';
  WHEN '.msf' THEN
    contentType := 'application/vnd.epson.msf';
  WHEN '.ssf' THEN
    contentType := 'application/vnd.epson.ssf';
  WHEN '.qam' THEN
    contentType := 'application/vnd.epson.quickanime';
  WHEN '.qfx' THEN
    contentType := 'application/vnd.intu.qfx';
  WHEN '.qt' THEN
    contentType := 'video/quicktime';
  WHEN '.rar' THEN
    contentType := 'application/x-rar-compressed';
  WHEN '.ram' THEN
    contentType := 'audio/x-pn-realaudio';
  WHEN '.rmp' THEN
    contentType := 'audio/x-pn-realaudio-plugin';
  WHEN '.rsd' THEN
    contentType := 'application/rsd+xml';
  WHEN '.rm' THEN
    contentType := 'application/vnd.rn-realmedia';
  WHEN '.bed' THEN
    contentType := 'application/vnd.realvnc.bed';
  WHEN '.mxl' THEN
    contentType := 'application/vnd.recordare.musicxml';
  WHEN '.musicxml' THEN
    contentType := 'application/vnd.recordare.musicxml+xml';
  WHEN '.rnc' THEN
    contentType := 'application/relax-ng-compact-syntax';
  WHEN '.rdz' THEN
    contentType := 'application/vnd.data-vision.rdz';
  WHEN '.rdf' THEN
    contentType := 'application/rdf+xml';
  WHEN '.rp9' THEN
    contentType := 'application/vnd.cloanto.rp9';
  WHEN '.jisp' THEN
    contentType := 'application/vnd.jisp';
  WHEN '.rtf' THEN
    contentType := 'application/rtf';
  WHEN '.rtx' THEN
    contentType := 'text/richtext';
  WHEN '.link66' THEN
    contentType := 'application/vnd.route66.link66+xml';
  WHEN '.rss, .xml' THEN
    contentType := 'application/rss+xml';
  WHEN '.shf' THEN
    contentType := 'application/shf+xml';
  WHEN '.st' THEN
    contentType := 'application/vnd.sailingtracker.track';
  WHEN '.svg' THEN
    contentType := 'image/svg+xml';
  WHEN '.sus' THEN
    contentType := 'application/vnd.sus-calendar';
  WHEN '.sru' THEN
    contentType := 'application/sru+xml';
  WHEN '.setpay' THEN
    contentType := 'application/set-payment-initiation';
  WHEN '.setreg' THEN
    contentType := 'application/set-registration-initiation';
  WHEN '.sema' THEN
    contentType := 'application/vnd.sema';
  WHEN '.semd' THEN
    contentType := 'application/vnd.semd';
  WHEN '.semf' THEN
    contentType := 'application/vnd.semf';
  WHEN '.see' THEN
    contentType := 'application/vnd.seemail';
  WHEN '.snf' THEN
    contentType := 'application/x-font-snf';
  WHEN '.spq' THEN
    contentType := 'application/scvp-vp-request';
  WHEN '.spp' THEN
    contentType := 'application/scvp-vp-response';
  WHEN '.scq' THEN
    contentType := 'application/scvp-cv-request';
  WHEN '.scs' THEN
    contentType := 'application/scvp-cv-response';
  WHEN '.sdp' THEN
    contentType := 'application/sdp';
  WHEN '.etx' THEN
    contentType := 'text/x-setext';
  WHEN '.movie' THEN
    contentType := 'video/x-sgi-movie';
  WHEN '.ifm' THEN
    contentType := 'application/vnd.shana.informed.formdata';
  WHEN '.itp' THEN
    contentType := 'application/vnd.shana.informed.formtemplate';
  WHEN '.iif' THEN
    contentType := 'application/vnd.shana.informed.interchange';
  WHEN '.ipk' THEN
    contentType := 'application/vnd.shana.informed.package';
  WHEN '.tfi' THEN
    contentType := 'application/thraud+xml';
  WHEN '.shar' THEN
    contentType := 'application/x-shar';
  WHEN '.rgb' THEN
    contentType := 'image/x-rgb';
  WHEN '.slt' THEN
    contentType := 'application/vnd.epson.salt';
  WHEN '.aso' THEN
    contentType := 'application/vnd.accpac.simply.aso';
  WHEN '.imp' THEN
    contentType := 'application/vnd.accpac.simply.imp';
  WHEN '.twd' THEN
    contentType := 'application/vnd.simtech-mindmapper';
  WHEN '.csp' THEN
    contentType := 'application/vnd.commonspace';
  WHEN '.saf' THEN
    contentType := 'application/vnd.yamaha.smaf-audio';
  WHEN '.mmf' THEN
    contentType := 'application/vnd.smaf';
  WHEN '.spf' THEN
    contentType := 'application/vnd.yamaha.smaf-phrase';
  WHEN '.teacher' THEN
    contentType := 'application/vnd.smart.teacher';
  WHEN '.svd' THEN
    contentType := 'application/vnd.svd';
  WHEN '.rq' THEN
    contentType := 'application/sparql-query';
  WHEN '.srx' THEN
    contentType := 'application/sparql-results+xml';
  WHEN '.gram' THEN
    contentType := 'application/srgs';
  WHEN '.grxml' THEN
    contentType := 'application/srgs+xml';
  WHEN '.ssml' THEN
    contentType := 'application/ssml+xml';
  WHEN '.skp' THEN
    contentType := 'application/vnd.koan';
  WHEN '.sgml' THEN
    contentType := 'text/sgml';
  WHEN '.sdc' THEN
    contentType := 'application/vnd.stardivision.calc';
  WHEN '.sda' THEN
    contentType := 'application/vnd.stardivision.draw';
  WHEN '.sdd' THEN
    contentType := 'application/vnd.stardivision.impress';
  WHEN '.smf' THEN
    contentType := 'application/vnd.stardivision.math';
  WHEN '.sdw' THEN
    contentType := 'application/vnd.stardivision.writer';
  WHEN '.sgl' THEN
    contentType := 'application/vnd.stardivision.writer-global';
  WHEN '.sm' THEN
    contentType := 'application/vnd.stepmania.stepchart';
  WHEN '.sit' THEN
    contentType := 'application/x-stuffit';
  WHEN '.sitx' THEN
    contentType := 'application/x-stuffitx';
  WHEN '.sdkm' THEN
    contentType := 'application/vnd.solent.sdkm+xml';
  WHEN '.xo' THEN
    contentType := 'application/vnd.olpc-sugar';
  WHEN '.au' THEN
    contentType := 'audio/basic';
  WHEN '.wqd' THEN
    contentType := 'application/vnd.wqd';
  WHEN '.sis' THEN
    contentType := 'application/vnd.symbian.install';
  WHEN '.smi' THEN
    contentType := 'application/smil+xml';
  WHEN '.xsm' THEN
    contentType := 'application/vnd.syncml+xml';
  WHEN '.bdm' THEN
    contentType := 'application/vnd.syncml.dm+wbxml';
  WHEN '.xdm' THEN
    contentType := 'application/vnd.syncml.dm+xml';
  WHEN '.sv4cpio' THEN
    contentType := 'application/x-sv4cpio';
  WHEN '.sv4crc' THEN
    contentType := 'application/x-sv4crc';
  WHEN '.sbml' THEN
    contentType := 'application/sbml+xml';
  WHEN '.tsv' THEN
    contentType := 'text/tab-separated-values';
  WHEN '.tiff' THEN
    contentType := 'image/tiff';
  WHEN '.tao' THEN
    contentType := 'application/vnd.tao.intent-module-archive';
  WHEN '.tar' THEN
    contentType := 'application/x-tar';
  WHEN '.tcl' THEN
    contentType := 'application/x-tcl';
  WHEN '.tex' THEN
    contentType := 'application/x-tex';
  WHEN '.tfm' THEN
    contentType := 'application/x-tex-tfm';
  WHEN '.tei' THEN
    contentType := 'application/tei+xml';
  WHEN '.txt' THEN
    contentType := 'text/plain';
  WHEN '.dxp' THEN
    contentType := 'application/vnd.spotfire.dxp';
  WHEN '.sfs' THEN
    contentType := 'application/vnd.spotfire.sfs';
  WHEN '.tsd' THEN
    contentType := 'application/timestamped-data';
  WHEN '.tpt' THEN
    contentType := 'application/vnd.trid.tpt';
  WHEN '.mxs' THEN
    contentType := 'application/vnd.triscape.mxs';
  WHEN '.t' THEN
    contentType := 'text/troff';
  WHEN '.tra' THEN
    contentType := 'application/vnd.trueapp';
  WHEN '.ttf' THEN
    contentType := 'application/x-font-ttf';
  WHEN '.ttl' THEN
    contentType := 'text/turtle';
  WHEN '.umj' THEN
    contentType := 'application/vnd.umajin';
  WHEN '.uoml' THEN
    contentType := 'application/vnd.uoml+xml';
  WHEN '.unityweb' THEN
    contentType := 'application/vnd.unity';
  WHEN '.ufd' THEN
    contentType := 'application/vnd.ufdl';
  WHEN '.uri' THEN
    contentType := 'text/uri-list';
  WHEN '.utz' THEN
    contentType := 'application/vnd.uiq.theme';
  WHEN '.ustar' THEN
    contentType := 'application/x-ustar';
  WHEN '.uu' THEN
    contentType := 'text/x-uuencode';
  WHEN '.vcs' THEN
    contentType := 'text/x-vcalendar';
  WHEN '.vcf' THEN
    contentType := 'text/x-vcard';
  WHEN '.vcd' THEN
    contentType := 'application/x-cdlink';
  WHEN '.vsf' THEN
    contentType := 'application/vnd.vsf';
  WHEN '.wrl' THEN
    contentType := 'model/vrml';
  WHEN '.vcx' THEN
    contentType := 'application/vnd.vcx';
  WHEN '.mts' THEN
    contentType := 'model/vnd.mts';
  WHEN '.vtu' THEN
    contentType := 'model/vnd.vtu';
  WHEN '.vis' THEN
    contentType := 'application/vnd.visionary';
  WHEN '.viv' THEN
    contentType := 'video/vnd.vivo';
  WHEN '.ccxml' THEN
    contentType := 'application/ccxml+xml,';
  WHEN '.vxml' THEN
    contentType := 'application/voicexml+xml';
  WHEN '.src' THEN
    contentType := 'application/x-wais-source';
  WHEN '.wbxml' THEN
    contentType := 'application/vnd.wap.wbxml';
  WHEN '.wbmp' THEN
    contentType := 'image/vnd.wap.wbmp';
  WHEN '.wav' THEN
    contentType := 'audio/x-wav';
  WHEN '.davmount' THEN
    contentType := 'application/davmount+xml';
  WHEN '.woff' THEN
    contentType := 'application/x-font-woff';
  WHEN '.wspolicy' THEN
    contentType := 'application/wspolicy+xml';
  WHEN '.webp' THEN
    contentType := 'image/webp';
  WHEN '.wtb' THEN
    contentType := 'application/vnd.webturbo';
  WHEN '.wgt' THEN
    contentType := 'application/widget';
  WHEN '.hlp' THEN
    contentType := 'application/winhlp';
  WHEN '.wml' THEN
    contentType := 'text/vnd.wap.wml';
  WHEN '.wmls' THEN
    contentType := 'text/vnd.wap.wmlscript';
  WHEN '.wmlsc' THEN
    contentType := 'application/vnd.wap.wmlscriptc';
  WHEN '.wpd' THEN
    contentType := 'application/vnd.wordperfect';
  WHEN '.stf' THEN
    contentType := 'application/vnd.wt.stf';
  WHEN '.wsdl' THEN
    contentType := 'application/wsdl+xml';
  WHEN '.xbm' THEN
    contentType := 'image/x-xbitmap';
  WHEN '.xpm' THEN
    contentType := 'image/x-xpixmap';
  WHEN '.xwd' THEN
    contentType := 'image/x-xwindowdump';
  WHEN '.der' THEN
    contentType := 'application/x-x509-ca-cert';
  WHEN '.fig' THEN
    contentType := 'application/x-xfig';
  WHEN '.xhtml' THEN
    contentType := 'application/xhtml+xml';
  WHEN '.xml' THEN
    contentType := 'application/xml';
  WHEN '.xdf' THEN
    contentType := 'application/xcap-diff+xml';
  WHEN '.xenc' THEN
    contentType := 'application/xenc+xml';
  WHEN '.xer' THEN
    contentType := 'application/patch-ops-error+xml';
  WHEN '.rl' THEN
    contentType := 'application/resource-lists+xml';
  WHEN '.rs' THEN
    contentType := 'application/rls-services+xml';
  WHEN '.rld' THEN
    contentType := 'application/resource-lists-diff+xml';
  WHEN '.xslt' THEN
    contentType := 'application/xslt+xml';
  WHEN '.xop' THEN
    contentType := 'application/xop+xml';
  WHEN '.xpi' THEN
    contentType := 'application/x-xpinstall';
  WHEN '.xspf' THEN
    contentType := 'application/xspf+xml';
  WHEN '.xul' THEN
    contentType := 'application/vnd.mozilla.xul+xml';
  WHEN '.xyz' THEN
    contentType := 'chemical/x-xyz';
  WHEN '.yaml' THEN
    contentType := 'text/yaml';
  WHEN '.yang' THEN
    contentType := 'application/yang';
  WHEN '.yin' THEN
    contentType := 'application/yin+xml';
  WHEN '.zir' THEN
    contentType := 'application/vnd.zul';
  WHEN '.zip' THEN
    contentType := 'application/zip';
  WHEN '.zmm' THEN
    contentType := 'application/vnd.handheld-entertainment+xml';
  WHEN '.zaz' THEN
    contentType := 'application/vnd.zzazz.deck+xml';
  ELSE
    contentType := 'application/octet-stream';
  END CASE;
RETURN contentType;
END;
/
